###### Imports and Settings

In [49]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
from collections import deque
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
pd.options.mode.chained_assignment = None  # default='warn'

# Comprehensive Plan Data Pull

In [50]:
#to read in... rb is read bite
with open('api_keys.pkl', 'rb') as keys_file:
        keys_dict_2 = pickle.load(keys_file)

In [51]:
#create a variable that contains your api key
api_key = keys_dict_2['CENSUS']
#api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'

In [52]:
GNRC = ['161', #Stewart
       '125', #Montgomery
       '083', #Houston
       '085', #Humphreys
       '043', #Dickson
       '021', #Cheatham
       '147', #Robertson
       '165', #Sumner
       '037', #Davidson
       '189', #Wilson
       '169', #Trousdale
       '187', #Williamson
       '149', #Rutherford
       '119'] #Maury

In [53]:
qlaces = ['1600000US4702180', #Ashland City: Cheatham
          '1600000US4739660', #Kingston Springs: Cheatham
          '1600000US4757480', #Pegram: Cheatham
          '1600000US4759560', #Pleasant View: Cheatham
          '1600000US4704620', #Belle Meade: Davidson
          '1600000US4705140', #Berry Hill: Davidson
          '1600000US4727020', #Forest Hills: Davidson
          '1600000US4729920', #Goodlettsville: Davidson/Sumner
          '1600000US4752006', #Nashville-Davidson metropolitan government (balance): Davidson
          '1600000US4754780', #Oak Hill: Davidson
          '1600000US4763140', #Ridgetop: Davidson/Robertson
          '1600000US4709880', #Burns: Dickson
          '1600000US4713080', #Charlotte: Dickson
          '1600000US4720620', #Dickson: Dickson
          '1600000US4769080', #Slayden: Dickson
          '1600000US4776860', #Vanleer: Dickson
          '1600000US4779980', #White Bluff: Dickson
          '1600000US4724320', #Erin: Houston
          '1600000US4773460', #Tennessee Ridge: Houston/Stewart
          '1600000US4744840', #McEwen: Humphreys
          '1600000US4752820', #New Johnsonville: Humphreys
          '1600000US4778560', #Waverly: Humphreys
          '1600000US4716540', #Columbia: Maury
          '1600000US4751080', #Mount Pleasant: Maury
          '1600000US4770580', #Spring Hill: Maury/Williamson
          '1600000US4715160', #Clarksville: Montgomery
          '1600000US4700200', #Adams: Robertson
          '1600000US4711980', #Cedar Hill: Robertson
          '1600000US4716980', #Coopertown: Robertson
          '1600000US4718420', #Cross Plains: Robertson
          '1600000US4730960', #Greenbrier: Robertson
          '1600000US4748980', #Millersville: Robertson/Sumner
          '1600000US4760280', #Portland: Robertson/Sumner
          '1600000US4770500', #Springfield: Robertson
          '1600000US4780200', #White House: Robertson/Sumner
          '1600000US4722360', #Eagleville: Rutherford
          '1600000US4741200', #La Vergne: Rutherford
          '1600000US4751560', #Murfreesboro: Rutherford
          '1600000US4769420', #Smyrna: Rutherford
          '1600000US4718820', #Cumberland City: Stewart
          '1600000US4721400', #Dover: Stewart
          '1600000US4728540', #Gallatin: Sumner
          '1600000US4733280', #Hendersonville: Sumner
          '1600000US4779420', #Westmoreland: Sumner
          '1600000US4708280', #Brentwood: Williamson
          '1600000US4725440', #Fairview: Williamson
          '1600000US4727740', #Franklin: Williamson
          '1600000US4753460', #Nolensville: Williamson
          '1600000US4773900', #Thompson's Station: Williamson
          '1600000US4741520', #Lebanon: Wilson
          '1600000US4750780', #Mount Juliet: Wilson
          '1600000US4778320'] #Watertown: Wilson

## Read In Data Guide

The "head" should never be more than 2 variables, and the "tail" never more than 2. Since we can pull 50 variables at once this means that we can systematically program in 46 variables for each pull, so that's:
+ dg1: ID's 1 - 46  
+ dg2: ID's 47-92  
+ dg3: ID's 93-138  
+ dg4: ID's 139-184  
+ dg5: ID's 185-230  
+ dg6: ID's 231-276  
+ dg7: ID's 277-322  
+ dg8: ID's 323-368  
+ dg9: ID's 369-414  
+ dg10: ID's 415-460  
+ dg11: ID's 461-506  
+ dg12: ID's 507-552  
+ dg13: ID's 553-598  

**This data guide stops at ID 554 as of 7/8/2022.**

In [78]:
dataguide = pd.read_csv('../data guides/DATA GUIDE ACS 2010.csv', dtype = str)
dataguide['ID'] = dataguide['ID'].astype(int)

In [79]:
dg1 = dataguide[dataguide['ID'].between(1, 46)]
dg2 = dataguide[dataguide['ID'].between(47, 92)]
dg3 = dataguide[dataguide['ID'].between(93, 138)]
dg4 = dataguide[dataguide['ID'].between(139, 184)]
dg5 = dataguide[dataguide['ID'].between(185, 230)]
dg6 = dataguide[dataguide['ID'].between(231, 276)]
dg7 = dataguide[dataguide['ID'].between(277, 322)]
dg8 = dataguide[dataguide['ID'].between(323, 368)]
dg9 = dataguide[dataguide['ID'].between(369, 414)]
dg10 = dataguide[dataguide['ID'].between(415, 460)]
dg11 = dataguide[dataguide['ID'].between(461, 506)]
dg12 = dataguide[dataguide['ID'].between(507, 552)]
dg13 = dataguide[dataguide['ID'].between(553, 598)]

## One Through Twenty Seven

In [56]:
# ONE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg1['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg1['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
onepull = df
print('Okay Finished')

Okay Finished

In [57]:
#placemarker
one = onepull

In [58]:
#TWO
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg2['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg2['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
twopull = df
print('Okay Finished')

Okay Finished

In [59]:
two = twopull

In [61]:
# THREE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg3['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg3['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
threepull = df
print('Okay Finished')

Okay Finished

In [62]:
three = threepull

In [63]:
# FOUR
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg4['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg4['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
fourpull = df
print('Okay Finished')

Okay Finished

In [64]:
four = fourpull

In [65]:
# FIVE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg5['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg5['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
fivepull = df
print('Okay Finished')

Okay Finished

In [66]:
five = fivepull

In [67]:
# SIX
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg6['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg6['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
sixpull = df
print('Okay Finished')

Okay Finished

In [68]:
six = sixpull

In [69]:
# SEVEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg7['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg7['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
sevenpull = df
print('Okay Finished')

Okay Finished

In [70]:
seven = sevenpull

In [71]:
# EIGHT
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg8['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg8['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
eightpull = df
print('Okay Finished')

Okay Finished

In [72]:
eight = eightpull

In [73]:
# NINE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg9['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg9['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
ninepull = df
print('Okay Finished')

Okay Finished

In [74]:
nine = ninepull

In [75]:
# TEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg10['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg10['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
tenpull = df
print('Okay Finished')

Okay Finished

In [76]:
ten = tenpull

In [81]:
# ELEVEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg11['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg11['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
elevenpull = df
print('Okay Finished')

Okay Finished

In [82]:
eleven = elevenpull

In [83]:
# TWELVE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg12['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg12['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
twelvepull = df
print('Okay Finished')

Okay Finished

In [84]:
twelve = twelvepull

In [85]:
# THIRTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg13['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg13['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "county:*"
predicates["in"]= "state:47"                                                             
data = requests.get(url_str, params= predicates)                                                                
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
df = df.loc[df['GeoFIPS'].isin(GNRC)]
#places call
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[places['GEO_ID'].isin(qlaces)]
df = df.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2010/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
df = df.append(state, ignore_index = True)
thirteenpull = df
print('Okay Finished')

Okay Finished

In [86]:
thirteen = thirteenpull

In [87]:
last = thirteen

In [88]:
dfs = [two,three,four,five,six,seven,eight,nine,ten,eleven,twelve]

In [89]:
for df in dfs:
    df = df.drop(columns = ['NAME','StateFIPS','GeoFIPS'], inplace = True)

In [90]:
one = one.drop(columns = ['StateFIPS','GeoFIPS'])
last = last.drop(columns = 'NAME')

In [91]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [92]:
dfs = [one, df_merged, last]
data = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [93]:
transp = data.transpose()
transp.columns = transp.iloc[0]

In [94]:
transp = transp.loc[transp['Stewart County, Tennessee'] != 'Stewart County, Tennessee']
transp = transp.loc[transp['Stewart County, Tennessee'] != '0500000US47161']

In [95]:
numcols = list(transp.columns)
numcols
transp[numcols] = transp[numcols].astype(float)

In [96]:
data = transp

In [97]:
GNRCCounties = [data['Stewart County, Tennessee'],data['Montgomery County, Tennessee'],data['Houston County, Tennessee'],data['Humphreys County, Tennessee'],
                data['Dickson County, Tennessee'],data['Cheatham County, Tennessee'],data['Robertson County, Tennessee'],data['Sumner County, Tennessee'],
                data['Davidson County, Tennessee'],data['Wilson County, Tennessee'],data['Trousdale County, Tennessee'],data['Williamson County, Tennessee'],
                data['Rutherford County, Tennessee']]
data['GNRC'] = sum(GNRCCounties)

In [98]:
MPOCounties = [data['Robertson County, Tennessee'],data['Sumner County, Tennessee'],data['Davidson County, Tennessee'],data['Wilson County, Tennessee'],
               data['Williamson County, Tennessee'],data['Rutherford County, Tennessee'],data['Maury County, Tennessee']]
data['MPO'] = sum(MPOCounties)

In [99]:
RuthInc = [data['Eagleville city, Tennessee'],data['La Vergne city, Tennessee'],data['Murfreesboro city, Tennessee'],data['Smyrna town, Tennessee']]
data['Rutherford Incorporated'] = sum(RuthInc)
data['Rutherford Unincorporated'] = data['Rutherford County, Tennessee'] - data['Rutherford Incorporated']
WilsonInc = [data['Lebanon city, Tennessee'],data['Mount Juliet city, Tennessee'],data['Watertown city, Tennessee']]
data['Wilson Incorporated'] = sum(WilsonInc)
data['Wilson Unincorporated'] = data['Wilson County, Tennessee'] - data['Wilson Incorporated']
CheathInc = [data['Ashland City town, Tennessee'],data['Kingston Springs town, Tennessee'],data['Pegram town, Tennessee'],data['Pleasant View city, Tennessee']]
data['Cheatham Incorporated'] = sum(CheathInc)
data['Cheatham Unincorporated'] = data['Cheatham County, Tennessee'] - data['Cheatham Incorporated']
DicksInc = [data['Burns town, Tennessee'],data['Charlotte town, Tennessee'],data['Dickson city, Tennessee'],data['Slayden town, Tennessee'],
            data['Vanleer town, Tennessee'],data['White Bluff town, Tennessee']]
data['Dickson Incorporated'] = sum(DicksInc)
data['Dickson Unincorporated'] = data['Dickson County, Tennessee'] - data['Dickson Incorporated']
HumphInc = [data['McEwen city, Tennessee'],data['New Johnsonville city, Tennessee'],data['Waverly city, Tennessee']]
data['Humphreys Incorporated'] = sum(HumphInc)
data['Humphreys Unincorporated'] = data['Humphreys County, Tennessee'] - data['Humphreys Incorporated']
data['Montgomery Incorporated'] = data['Clarksville city, Tennessee']
data['Montgomery Unincorporated'] = data['Montgomery County, Tennessee'] - data['Montgomery Incorporated']

In [100]:
ok = data.transpose().reset_index()

In [101]:
ok.head()

,NAME,agebysex_total_series,hhsize_avg,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,hhincome_total_series,hhincome_lessthan10000,hhincome_10to14999,hhincome_15to19999,hhincome_20to24999,hhincome_25to29999,hhincome_30to34999,hhincome_35to39999,hhincome_40to44999,hhincome_45to49999,hhincome_50to59999,hhincome_60to74999,hhincome_75to99999,hhincome_100to124999,hhincome125to149999,hhincome150to199999,hhincome200ormore,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,commute_total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,foreignborn_total,fb_europe,fb_asia,fb_africa,fb_oceania,fb_americas,fb_am_latinamerica,fb_am_northern,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_22to24_employed,lfstatus_mciv_22to24_unemployed,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,lfstatus_mciv_30to34_unemployed,lfstatus_mciv_35to44,lfstatus_mciv_35to44_employed,lfstatus_mciv_35to44_unemployed,lfstatus_mciv_45to54,lfstatus_mciv_45to54_employed,lfstatus_mciv_45to54_unemployed,lfstatus_mciv_55to59,lfstatus_mciv_55to59_employed,lfstatus_mciv_55to59_unemployed,lfstatus_mciv_60to61,lfstatus_mciv_60to61_employed,lfstatus_mciv_60to61_unemployed,lfstatus_mciv_62to64,lfstatus_mciv_62to64_employed,lfstatus_mciv_62to64_unemployed,lfstatus_mciv_65to69,lfstatus_mciv_65to69_employed,lfstatus_mciv_65to69_unemployed,lfstatus_mciv_70to74,lfstatus_mciv_70to74_employed,lfstatus_mciv_70to74_unemployed,lfstatus_mciv_75+,lfstatus_mciv_75+_employed,lfstatus_mciv_75+_unemployed,lfstatus_fciv_16to19,lfstatus_fciv_16to19_employed,lfstatus_fciv_16to19_unemployed,lfstatus_fciv_20to21,lfstatus_fciv_20to21_employed,lfstatus_fciv_20to21_unemployed,lfstatus_fciv_22to24,lfstatus_fciv_22to24_employed,lfstatus_fciv_22to24_unemployed,lfstatus_fciv_25to29,lfstatus_fciv_25to29_employed,lfstatus_fciv_25to29_unemployed,lfstatus_fciv_30to34,lfstatus_fciv_30to34_employed,lfstatus_fciv_30to34_unemployed,lfstatus_fciv_35to44,lfstatus_fciv_35to44_employed,lfstatus_fciv_35to44_unemployed,lfstatus_fciv_45to54,lfstatus_fciv_45to54_employed,lfstatus_fciv_45to54_unemployed,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+_employed,lfstatus_fciv_75+_unemployed,percapita_income,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information,industry_m_finance_insurance_realestate_rental,industry_m_finrent_finance_insurance,industry_m_finrent_realestate_rental,industry_m_professional_scientific_managementadmin_waste,industry_m_profwaste_professional_scientific_technicalservices,industry_m_profwaste_managementcompaniesenterprises,industry_m_adminandsupportandwaste,industry_m_educational_healthcare_socialassistance,industry_m_edsocial_educational,industry_m_edsocial_healthcare_socialassistance,industry_m_arts_entertainmentrec_accommodation_food,industry_m_artsaccom_arts_entertainmentrec,industry_m_artsaccom_accommodation_food,industry_m_otherservices_notpublicadmin,industry_m_publicadmin,industry_sexbyindustrycivilianpop_totalfemale,industry_f_agriculture_forestry_fishing_hunting_mining,industry_f_agmining_agriculture_forestry_fishing_hunting,industry_f_agmining_mining_quarrying_oilandgas,industry_f_construction,industry_f_manufacturing,industry_f_wholesaletrade,industry_f_retailtrade,industry_f_transportation_warehousing_utilities,industry_f_transut_transportation_warehousing,industry_f_transut_utilities,industry_f_information,industry_f_finance_insurance_realestate_rental,industry_f_finrent_finance_insurance,industry_f_finrent_realestate_rental,industry_f_professional_scientific_managementadmin_waste,industry_f_profwaste_professional_scientific_technicalservices,industry_f_profwaste_managementcompaniesenterprises,industry_f_adminandsupportandwaste,industry_f_educational_healthcare_socialassistance,industry_f_edsocial_educational,industry_f_edsocial_healthcare_socialassistance,industry_f_arts_entertainmentrec_accommodation_food,industry_f_artsaccom_arts_entertainmentrec,industry_f_artsaccom_accommodation_food,industry_f_otherservices_notpublicadmin,industry_f_publicadmin,occupation_sexbyoccupationcivilianpop_total_series,occupation_sexbyoccupationcivilianpop_totalmale,occupation_m_management,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_management,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educationtrainingandlibrary,occupation_f_artsdesignentertainmentsportsandmedia,occupation_f_healthcarepractitionersandtechnical,occupation_f_healthcaresupport,occupation_f_protectiveservice,occupation_f_foodprepandserving,occupation_f_buildingandgroundscleaningandmaintenance,occupation_f_personalcareandservice,occupation_f_salesandrelated,occupation_f_officeandadmin,occupation_f_farmingfishingandforestry,occupation_f_constructionandextraction,occupation_f_installationmaintenanceandrepair,occupation_f_production,occupation_f_transportation,occupation_f_materialmoving,language_languagebyabilitytospeakenglish_total5+_series,language_total_5to17,language_speakonlyenglish_5to17,language_speakspanish_5to17,language_speakspanish_speakenglishverywell_5to17,language_speakspanish_speakenglishwell_5to17,language_speakspanish_speakenglishnotwell_5to17,language_speakspanish_speakenglishnotatall_5to17,language_speakotherindoeuro_5to17,language_speakotherindoeuro_speakenglishverywell_5to17,language_speakotherindoeuro_speakenglishwell_5to17,language_speakotherindoeuro_speakenglishnotwell_5to17,language_speakotherindoeuro_speakenglishnotatall_5to17,language_speakasianpacificisland_5to17,language_speakasianpacificisland_speakenglishverywell_5to17,language_speakasianpacificisland_speakenglishwell_5to17,language_speakasianpacificisland_speakenglishnotwell_5to17,language_speakasianpacificisland_speakenglishnotatall_5to17,language_speakother_5to17,language_speakother_speakenglishverywell_5to17,language_speakother_speakenglishwell_5to17,language_speakother_speakenglishnotwell_5to17,language_speakother_speakenglishnotatall_5to17,language_total_18to64,language_speakonlyenglish_18to64,language_speakspanish_18to64,language_speakspanish_speakenglishverywell_18to64,language_speakspanish_speakenglishwell_18to64,language_speakspanish_speakenglishnotwell_18to64,language_speakspanish_speakenglishnotatall_18to64,language_speakotherindoeuro_18to64,language_speakotherindoeuro_speakenglishverywell_18to64,language_speakotherindoeuro_speakenglishwell_18to64,language_speakotherindoeuro_speakenglishnotwell_18to64,language_speakotherindoeuro_speakenglishnotatall_18to64,language_speakasianpacificisland_18to64,language_speakasianpacificisland_speakenglishverywell_18to64,language_speakasianpacificisland_speakenglishwell_18to64,language_speakasianpacificisland_speakenglishnotwell_18to64,language_speakasianpacificisland_speakenglishnotatall_18to64,language_speakother_18to64,language_speakother_speakenglishverywell_18to64,language_speakother_speakenglishwell_18to64,language_speakother_speakenglishnotwell_18to64,language_speakother_speakenglishnotatall_18to64,language_total_65+,language_speakonlyenglish_65+,language_speakspanish_65+,language_speakspanish_speakenglishverywell_65+,language_speakspanish_speakenglishwell_65+,language_speakspanish_speakenglishnotwell_65+,language_speakspanish_speakenglishnotatall_65+,language_speakotherindoeuro_65+,language_speakotherindoeuro_speakenglishverywell_65+,language_speakotherindoeuro_speakenglishwell_65+,language_speakotherindoeuro_speakenglishnotwell_65+,language_speakotherindoeuro_speakenglishnotatall_65+,language_speakasianpacificisland_65+,language_speakasianpacificisland_speakenglishverywell_65+,language_speakasianpacificisland_speakenglishwell_65+,language_speakasianpacificisland_speakenglishnotwell_65+,language_speakasianpacificisland_speakenglishnotatall_65+,language_speakother_65+,language_speakother_speakenglishverywell_65+,language_speakother_speakenglishwell_65+,language_speakother_speakenglishnotwell_65+,language_speakother_speakenglishnotatall_65+,veteran_total_series,veteran_total_veteran,veteran_total_nonveteran,veteran_male,veteran_m_veteran,veteran_m_nonveteran,veteran_m18to34,veteran_m18to34_veteran,veteran_m18to34_nonveteran,veteran_m35to54,veteran_m35to54_veteran,veteran_m35to54_nonveteran,veteran_m55to64,veteran_m55to64_veteran,veteran_m55to64_nonveteran,veteran_m65to74,veteran_m65to74_veteran,veteran_m65to74_nonveteran,veteran_m75+,veteran_m75+_veteran,veteran_m75+_nonveteran,veteran_female,veteran_f_veteran,veteran_f_nonveteran,veteran_f18to34,veteran_f18to34_veteran,veteran_f18to34_nonveteran,veteran_f35to54,veteran_f35to54_veteran,veteran_f35to54_nonveteran,veteran_f55to64,veteran_f55to64_veteran,veteran_f55to64_nonveteran,veteran_f65to74,veteran_f65to74_veteran,veteran_f65to74_nonveteran,veteran_f75+,veteran_f75+_veteran,veteran_f75+_nonveteran,traveltimemode_series_total,traveltimemode_lessthan10,traveltimemode_10to14,traveltimemode_15to19,traveltimemode_20to24,traveltimemode_25to29,traveltimemode_30to34,traveltimemode_35to44,traveltimemode_45to59,traveltimemode_60ormore,traveltimemode_cartruckvan_drovealone,traveltimemode_cartruckvan_drovealone_lessthan10,traveltimemode_cartruckvan_drovealone_10to14,traveltimemode_cartruckvan_drovealone_15to19,traveltimemode_cartruckvan_drovealone_20to24,traveltimemode_cartruckvan_drovealone_25to29,traveltimemode_cartruckvan_drovealone_30to34,traveltimemode_cartruckvan_drovealone_35to44,traveltimemode_cartruckvan_drovealone_45to59,traveltimemode_cartruckvan_drovealone_60ormore,traveltimemode_cartruckvan_carpooled,traveltimemode_cartruckvan_carpooled_lessthan10,traveltimemode_cartruckvan_carpooled_10to14,traveltimemode_cartruckvan_carpooled_15to19,traveltimemode_cartruckvan_carpooled_20to24,traveltimemode_cartruckvan_carpooled_25to29,traveltimemode_cartruckvan_carpooled_30to34,traveltimemode_cartruckvan_carpooled_35to44,traveltimemode_cartruckvan_carpooled_45to59,traveltimemode_cartruckvan_carpooled_60ormore,traveltimemode_publictransportationexcludingtaxi,traveltimemode_publictransportationexcludingtaxi_lessthan10,traveltimemode_publictransportationexcludingtaxi_10to14,traveltimemode_publictransportationexcludingtaxi_15to19,traveltimemode_publictransportationexcludingtaxi_20to24,traveltimemode_publictransportationexcludingtaxi_25to29,traveltimemode_publictransportationexcludingtaxi_30to34,traveltimemode_publictransportationexcludingtaxi_35to44,traveltimemode_publictransportationexcludingtaxi_45to59,traveltimemode_publictransportationexcludingtaxi_60ormore,traveltimemode_taximotorcyclebicyclewalkedother,traveltimemode_taximotorcyclebicyclewalkedother_lessthan10,traveltimemode_taximotorcyclebicyclewalkedorother_10to14,traveltimemode_taximotorcyclebicyclewalkedorother_15to19,traveltimemode_taximotorcyclebicyclewalkedorother_20to24,traveltimemode_taximotorcyclebicyclewalkedorother_25to29,traveltimemode_taximotorcyclebicyclewalkedorother_30to34,traveltimemode_taximotorcyclebicyclewalkedorother_35to44,traveltimemode_taximotorcyclebicyclewalkedorother_45to59,traveltimemode_taximotorcyclebicyclewalkedorother_60ormore,fb_total_series,fb_nativeborn,fb_foreignborn,fb_foreignborn_naturalizeduscitizen,fb_foreignborn_notauscitizen,attainment_totalbysex_over25_series,attainment_m,attainment_m_noschooling,attainment_m_nurseryschoolto4thgrade,attainment_m_5thto6thgrade,attainment_m_7thto8thgrade,attainment_m_9thgrade,attainment_m_10thgrade,attainment_m_11thgrade,attainment_m_12thgradenodiploma,attainment_m_highschooldiplomaorequivalent,attainment_m_somecollegelessthan1year,attainment_m_somecollege1ormoreyearsnodegree,attainment_m_associatesdegree,attainment_m_bachelorsdegree,attainment_m_mastersdegree,attainment_m_professionalschooldegree,attainment_m_doctoratedegree,attainment_f,attainment_f_noschooling,attainment_f_nurseryschoolto4thgrade,attainment_f_5thto6thgrade,attainment_f_7thto8thgrade,attainment_f_9thgrade,attainment_f_10thgrade,attainment_f_11thgrade,attainment_f_12thgradenodiploma,attainment_f_highschooldiplomaorequivalent,attainment_f_somecollegelessthan1year,attainment_f_somecollege1ormoreyearsnodegree,attainment_f_associatesdegree,attainment_f_bachelorsdegree,attainment_f_mastersdegree,attainment_f_professionalschooldegree,attainment_f_doctoratedegree,StateFIPS,GeoFIPS

In [56]:
ok.tail()

,NAME,agebysex_total_series,hhsize_avg,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,hhincome_total_series,hhincome_lessthan10000,hhincome_10to14999,hhincome_15to19999,hhincome_20to24999,hhincome_25to29999,hhincome_30to34999,hhincome_35to39999,hhincome_40to44999,hhincome_45to49999,hhincome_50to59999,hhincome_60to74999,hhincome_75to99999,hhincome_100to124999,hhincome125to149999,hhincome150to199999,hhincome200ormore,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,commute_total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,foreignborn_total,fb_europe,fb_asia,fb_africa,fb_oceania,fb_americas,fb_am_latinamerica,fb_am_northern,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_22to24_employed,lfstatus_mciv_22to24_unemployed,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,lfstatus_mciv_30to34_unemployed,lfstatus_mciv_35to44,lfstatus_mciv_35to44_employed,lfstatus_mciv_35to44_unemployed,lfstatus_mciv_45to54,lfstatus_mciv_45to54_employed,lfstatus_mciv_45to54_unemployed,lfstatus_mciv_55to59,lfstatus_mciv_55to59_employed,lfstatus_mciv_55to59_unemployed,lfstatus_mciv_60to61,lfstatus_mciv_60to61_employed,lfstatus_mciv_60to61_unemployed,lfstatus_mciv_62to64,lfstatus_mciv_62to64_employed,lfstatus_mciv_62to64_unemployed,lfstatus_mciv_65to69,lfstatus_mciv_65to69_employed,lfstatus_mciv_65to69_unemployed,lfstatus_mciv_70to74,lfstatus_mciv_70to74_employed,lfstatus_mciv_70to74_unemployed,lfstatus_mciv_75+,lfstatus_mciv_75+_employed,lfstatus_mciv_75+_unemployed,lfstatus_fciv_16to19,lfstatus_fciv_16to19_employed,lfstatus_fciv_16to19_unemployed,lfstatus_fciv_20to21,lfstatus_fciv_20to21_employed,lfstatus_fciv_20to21_unemployed,lfstatus_fciv_22to24,lfstatus_fciv_22to24_employed,lfstatus_fciv_22to24_unemployed,lfstatus_fciv_25to29,lfstatus_fciv_25to29_employed,lfstatus_fciv_25to29_unemployed,lfstatus_fciv_30to34,lfstatus_fciv_30to34_employed,lfstatus_fciv_30to34_unemployed,lfstatus_fciv_35to44,lfstatus_fciv_35to44_employed,lfstatus_fciv_35to44_unemployed,lfstatus_fciv_45to54,lfstatus_fciv_45to54_employed,lfstatus_fciv_45to54_unemployed,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+_employed,lfstatus_fciv_75+_unemployed,percapita_income,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information,industry_m_finance_insurance_realestate_rental,industry_m_finrent_finance_insurance,industry_m_finrent_realestate_rental,industry_m_professional_scientific_managementadmin_waste,industry_m_profwaste_professional_scientific_technicalservices,industry_m_profwaste_managementcompaniesenterprises,industry_m_adminandsupportandwaste,industry_m_educational_healthcare_socialassistance,industry_m_edsocial_educational,industry_m_edsocial_healthcare_socialassistance,industry_m_arts_entertainmentrec_accommodation_food,industry_m_artsaccom_arts_entertainmentrec,industry_m_artsaccom_accommodation_food,industry_m_otherservices_notpublicadmin,industry_m_publicadmin,industry_sexbyindustrycivilianpop_totalfemale,industry_f_agriculture_forestry_fishing_hunting_mining,industry_f_agmining_agriculture_forestry_fishing_hunting,industry_f_agmining_mining_quarrying_oilandgas,industry_f_construction,industry_f_manufacturing,industry_f_wholesaletrade,industry_f_retailtrade,industry_f_transportation_warehousing_utilities,industry_f_transut_transportation_warehousing,industry_f_transut_utilities,industry_f_information,industry_f_finance_insurance_realestate_rental,industry_f_finrent_finance_insurance,industry_f_finrent_realestate_rental,industry_f_professional_scientific_managementadmin_waste,industry_f_profwaste_professional_scientific_technicalservices,industry_f_profwaste_managementcompaniesenterprises,industry_f_adminandsupportandwaste,industry_f_educational_healthcare_socialassistance,industry_f_edsocial_educational,industry_f_edsocial_healthcare_socialassistance,industry_f_arts_entertainmentrec_accommodation_food,industry_f_artsaccom_arts_entertainmentrec,industry_f_artsaccom_accommodation_food,industry_f_otherservices_notpublicadmin,industry_f_publicadmin,occupation_sexbyoccupationcivilianpop_total_series,occupation_sexbyoccupationcivilianpop_totalmale,occupation_m_management,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_management,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educationtrainingandlibrary,occupation_f_artsdesignentertainmentsportsandmedia,occupation_f_healthcarepractitionersandtechnical,occupation_f_healthcaresupport,occupation_f_protectiveservice,occupation_f_foodprepandserving,occupation_f_buildingandgroundscleaningandmaintenance,occupation_f_personalcareandservice,occupation_f_salesandrelated,occupation_f_officeandadmin,occupation_f_farmingfishingandforestry,occupation_f_constructionandextraction,occupation_f_installationmaintenanceandrepair,occupation_f_production,occupation_f_transportation,occupation_f_materialmoving,language_languagebyabilitytospeakenglish_total5+_series,language_total_5to17,language_speakonlyenglish_5to17,language_speakspanish_5to17,language_speakspanish_speakenglishverywell_5to17,language_speakspanish_speakenglishwell_5to17,language_speakspanish_speakenglishnotwell_5to17,language_speakspanish_speakenglishnotatall_5to17,language_speakotherindoeuro_5to17,language_speakotherindoeuro_speakenglishverywell_5to17,language_speakotherindoeuro_speakenglishwell_5to17,language_speakotherindoeuro_speakenglishnotwell_5to17,language_speakotherindoeuro_speakenglishnotatall_5to17,language_speakasianpacificisland_5to17,language_speakasianpacificisland_speakenglishverywell_5to17,language_speakasianpacificisland_speakenglishwell_5to17,language_speakasianpacificisland_speakenglishnotwell_5to17,language_speakasianpacificisland_speakenglishnotatall_5to17,language_speakother_5to17,language_speakother_speakenglishverywell_5to17,language_speakother_speakenglishwell_5to17,language_speakother_speakenglishnotwell_5to17,language_speakother_speakenglishnotatall_5to17,language_total_18to64,language_speakonlyenglish_18to64,language_speakspanish_18to64,language_speakspanish_speakenglishverywell_18to64,language_speakspanish_speakenglishwell_18to64,language_speakspanish_speakenglishnotwell_18to64,language_speakspanish_speakenglishnotatall_18to64,language_speakotherindoeuro_18to64,language_speakotherindoeuro_speakenglishverywell_18to64,language_speakotherindoeuro_speakenglishwell_18to64,language_speakotherindoeuro_speakenglishnotwell_18to64,language_speakotherindoeuro_speakenglishnotatall_18to64,language_speakasianpacificisland_18to64,language_speakasianpacificisland_speakenglishverywell_18to64,language_speakasianpacificisland_speakenglishwell_18to64,language_speakasianpacificisland_speakenglishnotwell_18to64,language_speakasianpacificisland_speakenglishnotatall_18to64,language_speakother_18to64,language_speakother_speakenglishverywell_18to64,language_speakother_speakenglishwell_18to64,language_speakother_speakenglishnotwell_18to64,language_speakother_speakenglishnotatall_18to64,language_total_65+,language_speakonlyenglish_65+,language_speakspanish_65+,language_speakspanish_speakenglishverywell_65+,language_speakspanish_speakenglishwell_65+,language_speakspanish_speakenglishnotwell_65+,language_speakspanish_speakenglishnotatall_65+,language_speakotherindoeuro_65+,language_speakotherindoeuro_speakenglishverywell_65+,language_speakotherindoeuro_speakenglishwell_65+,language_speakotherindoeuro_speakenglishnotwell_65+,language_speakotherindoeuro_speakenglishnotatall_65+,language_speakasianpacificisland_65+,language_speakasianpacificisland_speakenglishverywell_65+,language_speakasianpacificisland_speakenglishwell_65+,language_speakasianpacificisland_speakenglishnotwell_65+,language_speakasianpacificisland_speakenglishnotatall_65+,language_speakother_65+,language_speakother_speakenglishverywell_65+,language_speakother_speakenglishwell_65+,language_speakother_speakenglishnotwell_65+,language_speakother_speakenglishnotatall_65+,veteran_total_series,veteran_total_veteran,veteran_total_nonveteran,veteran_male,veteran_m_veteran,veteran_m_nonveteran,veteran_m18to34,veteran_m18to34_veteran,veteran_m18to34_nonveteran,veteran_m35to54,veteran_m35to54_veteran,veteran_m35to54_nonveteran,veteran_m55to64,veteran_m55to64_veteran,veteran_m55to64_nonveteran,veteran_m65to74,veteran_m65to74_veteran,veteran_m65to74_nonveteran,veteran_m75+,veteran_m75+_veteran,veteran_m75+_nonveteran,veteran_female,veteran_f_veteran,veteran_f_nonveteran,veteran_f18to34,veteran_f18to34_veteran,veteran_f18to34_nonveteran,veteran_f35to54,veteran_f35to54_veteran,veteran_f35to54_nonveteran,veteran_f55to64,veteran_f55to64_veteran,veteran_f55to64_nonveteran,veteran_f65to74,veteran_f65to74_veteran,veteran_f65to74_nonveteran,veteran_f75+,veteran_f75+_veteran,veteran_f75+_nonveteran,traveltimemode_series_total,traveltimemode_lessthan10,traveltimemode_10to14,traveltimemode_15to19,traveltimemode_20to24,traveltimemode_25to29,traveltimemode_30to34,traveltimemode_35to44,traveltimemode_45to59,traveltimemode_60ormore,traveltimemode_cartruckvan,traveltimemode_cartruckvan_lessthan10,traveltimemode_cartruckvan_10to14,traveltimemode_cartruckvan_15to19,traveltimemode_cartruckvan_20to24,traveltimemode_cartruckvan_25to29,traveltimemode_cartruckvan_30to34,traveltimemode_cartruckvan_35to44,traveltimemode_cartruckvan_45to59,traveltimemode_cartruckvan_60ormore,traveltimemode_cartruckvan_drovealone,traveltimemode_cartruckvan_drovealone_lessthan10,traveltimemode_cartruckvan_drovealone_10to14,traveltimemode_cartruckvan_drovealone_15to19,traveltimemode_cartruckvan_drovealone_20to24,traveltimemode_cartruckvan_drovealone_25to29,traveltimemode_cartruckvan_drovealone_30to34,traveltimemode_cartruckvan_drovealone_35to44,traveltimemode_cartruckvan_drovealone_45to59,traveltimemode_cartruckvan_drovealone_60ormore,traveltimemode_cartruckvan_carpooled,traveltimemode_cartruckvan_carpooled_lessthan10,traveltimemode_cartruckvan_carpooled_10to14,traveltimemode_cartruckvan_carpooled_15to19,traveltimemode_cartruckvan_carpooled_20to24,traveltimemode_cartruckvan_carpooled_25to29,traveltimemode_cartruckvan_carpooled_30to34,traveltimemode_cartruckvan_carpooled_35to44,traveltimemode_cartruckvan_carpooled_45to59,traveltimemode_cartruckvan_carpooled_60ormore,traveltimemode_publictransportationexcludingtaxi,traveltimemode_publictransportationexcludingtaxi_lessthan10,traveltimemode_publictransportationexcludingtaxi_10to14,traveltimemode_publictransportationexcludingtaxi_15to19,traveltimemode_publictransportationexcludingtaxi_20to24,traveltimemode_publictransportationexcludingtaxi_25to29,traveltimemode_publictransportationexcludingtaxi_30to34,traveltimemode_publictransportationexcludingtaxi_35to44,traveltimemode_publictransportationexcludingtaxi_45to59,traveltimemode_publictransportationexcludingtaxi_60ormore,traveltimemode_walked,traveltimemode_walked_lessthan10,traveltimemode_walked_10to14,traveltimemode_walked_15to19,traveltimemode_walked_20to24,traveltimemode_walked_25to29,traveltimemode_walked_30to34,traveltimemode_walked_35to44,traveltimemode_walked_45to59,traveltimemode_walked_60ormore,traveltimemode_taximotorcyclebicycleother,traveltimemode_taximotorcyclebicycleother_lessthan10,traveltimemode_taximotorcyclebicycleorother_10to14,traveltimemode_taximotorcyclebicycleorother_15to19,traveltimemode_taximotorcyclebicycleorother_20to24,traveltimemode_taximotorcyclebicycleorother_25to29,traveltimemode_taximotorcyclebicycleorother_30to34,traveltimemode_taximotorcyclebicycleorother_35to44,traveltimemode_taximotorcyclebicycleorother_45to59,traveltimemode_taximotorcyclebicycleorother_60ormore,fb_total_series,fb_nativeborn,fb_foreignborn,fb_foreignborn_naturalizeduscitizen,fb_foreignborn_notauscitizen,StateFIPS,GeoFIPS

In [102]:
ok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Columns: 547 entries, NAME to GeoFIPS
dtypes: float64(546), object(1)
memory usage: 346.3+ KB

In [103]:
ok.to_csv('../data/ACS20105YR.csv', index = False)