###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
from collections import deque
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
def percent(x, y):
    return (x/y)*100

## Calculations

## Population + Projections Summary: 
### Race/Ethnicity #s   
+ White Alone  
+ Black/African American Alone  
+ American Indian Alaska Native Alone  
+ Asian Alone  
+ Native Hawaiian/Other Pacific Islander Alone  
+ Some Other Race Alone  
+ Two or More Races  
+ Hispanic/Latino  
+ White, Not Hispanic/Latino  
+ Total Minority (non-white, non Hispanic/Latino)  
## Household Summary:  
### Occupancy Status, and Percentages  
+ Occupancy Total Households
+ Occupied  
+ Vacant

In [3]:
data = pd.read_csv('../../data/PL2020.csv')

In [4]:
data['Population'] = data['pop']
data = data.drop(columns = ['pop'])

#race and ethnicity
#White Alone
data['White Alone'] = data['raceeth_white_alone']
data['White Alone %'] = percent(data['White Alone'], data['Population'])
#Population not White
data['Non-White Population: Race'] = data['Population'] - data['White Alone']
#Black or African American Alone 
data['Black or African American Alone'] = data['raceeth_blackafricanamerican_alone']
data['Black or African American Alone %'] = percent(data['Black or African American Alone'], data['Population'])
data['Black or African American Alone % Non-White Population'] = percent(data['Black or African American Alone'], data['Non-White Population: Race'])
#American Indian and Alaska Native Alone
data['American Indian Alaska Native Alone'] = data['raceeth_americanindianalaskanative_alone']
data['American Indian Alaska Native Alone %'] = percent(data['American Indian Alaska Native Alone'], data['Population'])
data['American Indian Alaska Native Alone % Non-White Population'] = percent(data['American Indian Alaska Native Alone'], data['Non-White Population: Race'])
#Asian Alone
data['Asian Alone'] = data['raceeth_asian_alone']
data['Asian Alone %'] = percent(data['Asian Alone'], data['Population'])
data['Asian Alone % Non-White Population'] = percent(data['Asian Alone'], data['Non-White Population: Race'])
#Native Hawaiian Other Pacific Islander Alone
data['Native Hawaiian Other Pacific Islander Alone'] = data['raceeth_nativehawaiianotherpacificislander_alone']
data['Native Hawaiian Other Pacific Islander Alone %'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Population'])
data['Native Hawaiian Other Pacific Islander Alone % Non-White Population'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Non-White Population: Race'])
#Some Other Race Alone
data['Some Other Race Alone'] = data['raceeth_someotherrace_alone']
data['Some Other Race Alone %'] = percent(data['Some Other Race Alone'], data['Population'])
data['Some Other Race Alone % Non-White Population'] = percent(data['Some Other Race Alone'], data['Non-White Population: Race'])
#Two or More Races
data['Two or More Races'] = data['raceeth_twoormoreraces_alone']
data['Two or More Races %'] = percent(data['Two or More Races'], data['Population'])
data['Two or More Races % Non-White Population'] = percent(data['Two or More Races'], data['Non-White Population: Race'])
#Hispanic or Latino
data['Hispanic or Latino'] = data['raceeth_hispanicorlatino']
data['Hispanic or Latino %'] = percent(data['Hispanic or Latino'], data['Population'])
#not hispanic or latino
data['Not Hispanic or Latino'] = data['Population'] - data['Hispanic or Latino']
data['Not Hispanic or Latino %'] = percent(data['Not Hispanic or Latino'], data['Population'])
#Data Minority
data['Minority'] = data['Population'] - data['raceeth_whitealone_nothispanicorlatino']
data['Minority %'] = percent(data['Minority'], data['Population'])
#not minority
data['White Alone Not Hispanic or Latino'] = data['raceeth_whitealone_nothispanicorlatino']
data['White Alone Not Hispanic or Latino %'] = percent(data['White Alone Not Hispanic or Latino'], data['Population'])
cols = ['raceeth_total_series','raceeth_white_alone','raceeth_blackafricanamerican_alone','raceeth_americanindianalaskanative_alone','raceeth_asian_alone',
        'raceeth_nativehawaiianotherpacificislander_alone','raceeth_someotherrace_alone','raceeth_twoormoreraces_alone','raceeth_hispanicorlatino',
        'raceeth_whitealone_nothispanicorlatino']
data = data.drop(columns = cols)
#occupancy
data['Occupancy:Total Households'] = data['occupancy_total_series']
data['Occupancy:Occupied Units'] = data['occupancy_occupiedunits']
data['Occupancy%:Occupied Units'] = percent(data['Occupancy:Occupied Units'], data['Occupancy:Total Households'])
data['Occupancy:Vacant Units'] = data['occupancy_vacantunits']
data['Occupancy%:Vacant Units'] = percent(data['Occupancy:Vacant Units'], data['Occupancy:Total Households'])
cols = ['occupancy_total_series','occupancy_occupiedunits','occupancy_vacantunits', 'units_allhousing']
data = data.drop(columns = cols)
data = data.drop(columns = ['StateFIPS', 'GeoFIPS'])
data.head()

,NAME,Population,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units
0,"Montgomery County, Tennessee",220069.0,137775.0,62.605365,82294.0,44569.0,20.252285,54.158262,1154.0,0.524381,1.402289,5202.0,2.363804,6.321238,1000.0,0.454403,1.215155,7890.0,3.585239,9.587576,22479.0,10.214524,27.315479,22934.0,10.421277,197135.0,89.578723,88775.0,40.339621,131294.0,59.660379,85714.0,79841.0,93.148144,5873.0,6.851856
1,"Rutherford County, Tennessee",341486.0,226227.0,66.247811,115259.0,53977.0,15.806505,46.831050,1739.0,0.509245,1.508776,12538.0,3.671600,10.878109,254.0,0.074381,0.220373,19755.0,5.785010,17.139659,26996.0,7.905449,23.422032,38317.0,11.220665,303169.0,88.779335,122292.0,35.811717,219194.0,64.188283,131216.0,124465.0,94.855048,6751.0,5.144952
2,"Sumner County, Tennessee",196281.0,158075.0,80.535049,38206.0,15740.0,8.019115,41.197718,711.0,0.362236,1.860964,2956.0,1.506004,7.737005,119.0,0.060627,0.311469,5321.0,2.710909,13.927132,13359.0,6.806059,34.965712,12870.0,6.556926,183411.0,93.443074,41112.0,20.945481,155169.0,79.054519,78995.0,74472.0,94.274321,4523.0,5.725679
3,"Trousdale County, Tennessee",11615.0,8883.0,76.478691,2732.0,1922.0,16.547568,70.351391,30.0,0.258287,1.098097,27.0,0.232458,0.988287,0.0,0.000000,0.000000,205.0,1.764959,7.503660,548.0,4.718037,20.058565,375.0,3.228584,11240.0,96.771416,2829.0,24.356436,8786.0,75.643564,3749.0,3469.0,92.531342,280.0,7.468658
4,"Williamson County, Tennessee",247726.0,203600.0,82.187578,44126.0,9876.0,3.986663,22.381362,574.0,0.231708,1.300820,12953.0,5.228761,29.354576,117.0,0.047230,0.265150,5172.0,2.087791,11.720981,15434.0,6.230271,34.977111,14261.0,5.756764,233465.0,94.243236,47318.0,19.100942,200408.0,80.899058,91133.0,86884.0,95.337584,4249.0,4.662416

In [5]:
suffix = data.set_index('NAME')
suffix = suffix.add_suffix(' 2020')
suffix = suffix.reset_index()
suffix.head(3)

,NAME,Population 2020,White Alone 2020,White Alone % 2020,Non-White Population: Race 2020,Black or African American Alone 2020,Black or African American Alone % 2020,Black or African American Alone % Non-White Population 2020,American Indian Alaska Native Alone 2020,American Indian Alaska Native Alone % 2020,American Indian Alaska Native Alone % Non-White Population 2020,Asian Alone 2020,Asian Alone % 2020,Asian Alone % Non-White Population 2020,Native Hawaiian Other Pacific Islander Alone 2020,Native Hawaiian Other Pacific Islander Alone % 2020,Native Hawaiian Other Pacific Islander Alone % Non-White Population 2020,Some Other Race Alone 2020,Some Other Race Alone % 2020,Some Other Race Alone % Non-White Population 2020,Two or More Races 2020,Two or More Races % 2020,Two or More Races % Non-White Population 2020,Hispanic or Latino 2020,Hispanic or Latino % 2020,Not Hispanic or Latino 2020,Not Hispanic or Latino % 2020,Minority 2020,Minority % 2020,White Alone Not Hispanic or Latino 2020,White Alone Not Hispanic or Latino % 2020,Occupancy:Total Households 2020,Occupancy:Occupied Units 2020,Occupancy%:Occupied Units 2020,Occupancy:Vacant Units 2020,Occupancy%:Vacant Units 2020
0,"Montgomery County, Tennessee",220069.0,137775.0,62.605365,82294.0,44569.0,20.252285,54.158262,1154.0,0.524381,1.402289,5202.0,2.363804,6.321238,1000.0,0.454403,1.215155,7890.0,3.585239,9.587576,22479.0,10.214524,27.315479,22934.0,10.421277,197135.0,89.578723,88775.0,40.339621,131294.0,59.660379,85714.0,79841.0,93.148144,5873.0,6.851856
1,"Rutherford County, Tennessee",341486.0,226227.0,66.247811,115259.0,53977.0,15.806505,46.831050,1739.0,0.509245,1.508776,12538.0,3.671600,10.878109,254.0,0.074381,0.220373,19755.0,5.785010,17.139659,26996.0,7.905449,23.422032,38317.0,11.220665,303169.0,88.779335,122292.0,35.811717,219194.0,64.188283,131216.0,124465.0,94.855048,6751.0,5.144952
2,"Sumner County, Tennessee",196281.0,158075.0,80.535049,38206.0,15740.0,8.019115,41.197718,711.0,0.362236,1.860964,2956.0,1.506004,7.737005,119.0,0.060627,0.311469,5321.0,2.710909,13.927132,13359.0,6.806059,34.965712,12870.0,6.556926,183411.0,93.443074,41112.0,20.945481,155169.0,79.054519,78995.0,74472.0,94.274321,4523.0,5.725679

In [6]:
tidy = data
tidy.head(3)

,NAME,Population,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units
0,"Montgomery County, Tennessee",220069.0,137775.0,62.605365,82294.0,44569.0,20.252285,54.158262,1154.0,0.524381,1.402289,5202.0,2.363804,6.321238,1000.0,0.454403,1.215155,7890.0,3.585239,9.587576,22479.0,10.214524,27.315479,22934.0,10.421277,197135.0,89.578723,88775.0,40.339621,131294.0,59.660379,85714.0,79841.0,93.148144,5873.0,6.851856
1,"Rutherford County, Tennessee",341486.0,226227.0,66.247811,115259.0,53977.0,15.806505,46.831050,1739.0,0.509245,1.508776,12538.0,3.671600,10.878109,254.0,0.074381,0.220373,19755.0,5.785010,17.139659,26996.0,7.905449,23.422032,38317.0,11.220665,303169.0,88.779335,122292.0,35.811717,219194.0,64.188283,131216.0,124465.0,94.855048,6751.0,5.144952
2,"Sumner County, Tennessee",196281.0,158075.0,80.535049,38206.0,15740.0,8.019115,41.197718,711.0,0.362236,1.860964,2956.0,1.506004,7.737005,119.0,0.060627,0.311469,5321.0,2.710909,13.927132,13359.0,6.806059,34.965712,12870.0,6.556926,183411.0,93.443074,41112.0,20.945481,155169.0,79.054519,78995.0,74472.0,94.274321,4523.0,5.725679

In [7]:
suffix.to_csv('../../data/Suffix2020PL.csv', index = False)
tidy.to_csv('../../data/Tidy2020PL.csv', index = False)