###### Imports and Settings

In [3]:
import pandas as pd
#import geopandas as gpd
import numpy as np
import requests
import io
import pickle
import matplotlib.pyplot as plt
from collections import deque
from functools import reduce
%matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

###### Functions

In [4]:
#function for percent of whole
def percent(x, y):
    try:
        return round((x/y)*100, 2)
    except ZeroDivisionError:
        return 666
#function for population density
def populationdensity(x, y):
    try:
        return round(x/y, 2)
    except ZeroDivisionError:
        return 666

# Comprehensive Plan Data Pull  

The following API calls are designed to streamline the data pulls for the comprehensive plans for any geography. For the sake of simplicity, there are three separate documents for ACS variables, Decennial 2000 SF3 variables, and Decennial SF1 variables. This document contains ACS 5-Year Estimate variables. This document does contain one variable from the ACS 5-Year Subject Tables: S0801_C01_046E, mean travel-time to work.

In [5]:
#to read in... rb is read bite
with open('api_keys.pkl', 'rb') as keys_file:
        keys_dict_2 = pickle.load(keys_file)

In [6]:
#create a variable that contains your api key
api_key = keys_dict_2['CENSUS']
#api_key = '24fc7d81b74510d599f702dbd408fb18e1466d81'

In [7]:
GNRC = ['161', #Stewart
       '125', #Montgomery
       '083', #Houston
       '085', #Humphreys
       '043', #Dickson
       '021', #Cheatham
       '147', #Robertson
       '165', #Sumner
       '037', #Davidson
       '189', #Wilson
       '169', #Trousdale
       '187', #Williamson
       '149', #Rutherford
       '119'] #Maury

## Read In Data Guide

The "head" should never be more than 2 variables, and the "tail" never more than 2. Since we can pull 50 variables at once this means that we can systematically program in 46 variables for each pull, so that's:
+ dg1: ID's 1 - 46  
+ dg2: ID's 47-92  
+ dg3: ID's 93-138  
+ dg4: ID's 139-184  
+ dg5: ID's 185-230  
+ dg6: ID's 231-276  
+ dg7: ID's 277-322  
+ dg8: ID's 323-368  
+ dg9: ID's 369-414  
+ dg10: ID's 415-460  
+ dg11: ID's 461-506  
+ dg12: ID's 507-552  
+ dg13: ID's 553-598  
+ dg14: ID's 599-644  
+ dg15: ID's 645-690  
+ dg16: ID's 691-736  
+ dg17: ID's 737-782  
+ dg18: ID's 783-828 
+ dg19: ID's 829 - 874  
+ dg20: ID's 875 - 920  
+ dg21: ID's 921 - 966  
+ dg22: ID's 967 - 1012  
+ dg23: ID's 1013 - 1058  
+ dg24: ID's 1059 - 1104  
+ dg25: ID's 1105 - 1150  
+ dg26: ID's 1151 - 1196  
+ dg27: ID's 1197 - 1242

**This data guide stops at ID 1203 as of 6/28/2022.**

In [140]:
dataguide = pd.read_csv('../data guides/DATA GUIDE ACS.csv', dtype = str)
dataguide['ID'] = dataguide['ID'].astype(int)

In [141]:
dg1 = dataguide[dataguide['ID'].between(1, 46)]
dg2 = dataguide[dataguide['ID'].between(47, 92)]
dg3 = dataguide[dataguide['ID'].between(93, 138)]
dg4 = dataguide[dataguide['ID'].between(139, 184)]
dg5 = dataguide[dataguide['ID'].between(185, 230)]
dg6 = dataguide[dataguide['ID'].between(231, 276)]
dg7 = dataguide[dataguide['ID'].between(277, 322)]
dg8 = dataguide[dataguide['ID'].between(323, 368)]
dg9 = dataguide[dataguide['ID'].between(369, 414)]
dg10 = dataguide[dataguide['ID'].between(415, 460)]
dg11 = dataguide[dataguide['ID'].between(461, 506)]
dg12 = dataguide[dataguide['ID'].between(507, 552)]
dg13 = dataguide[dataguide['ID'].between(553, 598)]
dg14 = dataguide[dataguide['ID'].between(599, 644)]
dg15 = dataguide[dataguide['ID'].between(645, 690)]
dg16 = dataguide[dataguide['ID'].between(691, 736)]
dg17 = dataguide[dataguide['ID'].between(737, 782)]
dg18 = dataguide[dataguide['ID'].between(783, 828)]
dg19 = dataguide[dataguide['ID'].between(829, 874)]
dg20 = dataguide[dataguide['ID'].between(875, 920)]
dg21 = dataguide[dataguide['ID'].between(921, 966)]
dg22 = dataguide[dataguide['ID'].between(967, 1012)]
dg23 = dataguide[dataguide['ID'].between(1013, 1058)]
dg24 = dataguide[dataguide['ID'].between(1059, 1104)]
dg25 = dataguide[dataguide['ID'].between(1105, 1150)]
dg26 = dataguide[dataguide['ID'].between(1151, 1196)]
dg27 = dataguide[dataguide['ID'].between(1197, 1242)]

## One Through Twenty Seven

In [215]:
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg1['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg1['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)

url_str= 'https://api.census.gov/data/2009/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)

In [212]:
places.head(503)

,NAME,GEO_ID,agebysex_total_series,age_total_male,age_m_u5,age_m_5to9,age_m_10to14,age_m_15to17,age_m_18to19,age_m_20,age_m_21,age_m_22to24,age_m_25to29,age_m_30to34,age_m_35to39,age_m_40to44,age_m_45to49,age_m_50to54,age_m_55to59,age_m_60to61,age_m_62to64,age_m_65to66,age_m_67to69,age_m_70to74,age_m_75to79,age_m_80to84,age_m_85+,age_total_female,age_f_u5,age_f_5to9,age_f_10to14,age_f_15to17,age_f_18to19,age_f_20,age_f_21,age_f_22to24,age_f_25to29,age_f_30to34,age_f_35to39,age_f_40to44,age_f_45to49,age_f_50to54,age_f_55to59,age_f_60to61,age_f_62to64,age_f_65to66,age_f_67to69,age_f_70to74,StateFIPS,GeoFIPS
0,"Mount Carmel town, Tennessee",1600000US4750580,5356,2537,121,102,185,49,123,49,76,53,140,137,123,138,255,183,245,71,106,70,77,122,88,24,0,2819,212,84,85,147,0,54,63,53,109,139,226,238,346,282,118,69,117,88,66,208,47,50580
1,"Mount Juliet city, Tennessee",1600000US4750780,20501,10255,831,991,773,476,233,204,64,307,920,884,856,809,898,606,520,178,149,144,109,157,36,56,54,10246,1072,685,703,612,255,83,134,305,699,1015,845,639,722,761,538,173,122,99,213,148,47,50780
2,"Mount Pleasant city, Tennessee",1600000US4751080,4451,2194,199,168,150,162,160,12,0,120,41,309,50,122,38,165,119,27,84,19,47,88,70,31,13,2257,43,129,144,129,111,21,66,47,95,174,77,207,193,202,119,31,40,58,31,163,47,51080
3,"Munford city, Tennessee",1600000US4751540,6304,3006,173,143,334,145,61,25,0,196,187,93,182,313,207,205,304,13,87,16,79,87,83,59,14,3298,144,222,336,102,63,0,20,198,132,191,278,230,390,271,213,15,116,31,58,124,47,51540
4,"Murfreesboro city, Tennessee",1600000US4751560,97423,48072,3274,3186,3159,1898,2247,1607,1060,3016,6103,4099,3157,3384,3010,2365,1797,632,694,506,672,809,542,501,354,49351,3002,3132,3101,1672,2323,1531,1211,2807,5846,3875,3315,3470,2973,2514,2051,655,953,580,912,959,47,51560
5,Nashville-Davidson metropolitan government (ba...,1600000US4752006,592497,287475,22375,17907,16503,9783,8564,4744,4641,13540,29985,25245,22516,20956,20648,18703,15587,5446,5966,3451,4167,6065,5002,3242,2439,305022,21743,17637,16036,9641,8742,3955,4714,14374,30096,25711,20807,21214,21277,20031,18004,5550,7112,4033,5236,8654,47,52006
6,"Newbern town, Tennessee",1600000US4752400,3117,1316,105,67,194,61,11,0,18,22,121,127,44,148,49,85,35,66,29,18,30,18,44,0,24,1801,166,72,162,81,121,0,11,23,124,142,136,99,160,54,97,25,48,19,0,86,47,52400
7,"New Hope city, Tennessee",1600000US4752780,923,426,36,23,20,18,15,2,10,19,10,23,30,47,51,20,47,17,3,0,11,5,8,6,5,497,34,39,48,43,9,1,0,7,32,29,33,39,39,46,40,8,12,0,4,16,47,52780
8,"New Johnsonville city, Tennessee",1600000US4752820,1694,869,43,52,51,47,20,2,13,4,37,42,94,94,45,43,111,12,56,14,30,33,8,10,8,825,32,50,44,27,18,2,4,22,34,42,102,55,34,82,93,25,37,11,31,35,47,52820
9,"New Market town, Tennessee",1600000US4752940,1431,826,60,66,31,17,31,7,0,26,64,55,84,99,50,81,41,17,21,14,2,22,25,13,0,605,4,24,81,4,4,2,5,12,42,41,52,43,73,33,62,7,42,17,4,13,47,52940
10,"Newport city, Tennessee",1600000US4753000,7420,3436,162,228,189,137,161,58,19,145,218,222,219,281,254,207,204,108,154,57,36,169,107,49,52,3984,238,146,162,222,96,20,14,39,204,183,329,208,395,353,433,67,192,86,81,150,47,53000
11,"New Tazewell town, Tennessee",1600000US4753140,2863,1370,114,67,66,23,0,20,15,121,114,138,35,70,130,54,146,59,42,11,29,88,15,13,0,1493,78,17,44,0,47,0,0,165,36,81,58,26,70,188,41,57,100,34,63,160,47,53140
12,"Niota city, Tennessee",1600000US4753380,868,401,27,0,41,29,13,0,0,22,14,23,24,28,66,39,17,12,13,5,2,9,8,3,6,467,41,18,22,30,0,7,3,8,55,8,32,56,38,23,36,10,16,3,8,19,47,53380
13,"Nolensville town, Tennessee",1600000US4753460,3025,1475,98,167,112,67,16,62,9,23,70,90,146,108,151,119,70,32,19,10,26,17,31,22,10,1550,110,132,141,74,45,17,9,19,90,71,129,157,143,122,60,29,20,12,38,57,47,53460
14,"Normandy town, Tennessee",1600000US4753580,203,90,7,8,5,11,0,0,4,2,7,17,0,2,1,7,2,2,15,0,0,0,0,0,0,113,7,15,10,9,3,0,0,8,0,0,13,6,6,5,10,3,10,0,0,0,47,53580
15,"Norris city, Tennessee",1600000US4753600,1509,757,27,3,71,11,22,3,11,12,15,96,33,66,46,62,61,9,37,11,18,65,10,56,12,752,3,36,25,37,36,4,0,13,49,13,36,27,60,93,93,28,26,14,29,75,47,53600
16,"Oakdale town, Tennessee",1600000US4754280,269,112,13,6,5,4,0,0,0,2,9,7,3,11,8,20,5,0,7,5,3,4,0,0,0,157,8,13,18,6,2,0,10,4,5,5,23,15,9,6,3,2,21,2,0,0,47,54280
17,"Oak Grove CDP, Tennessee",1600000US4754700,3639,1814,100,73,41,60,37,0,21,101,139,135,256,103,35,122,236,50,67,50,65,33,55,17,18,1825,111,125,106,28,18,9,54,70,150,143,110,155,138,179,162,39,57,27,14,59,47,54700
18,"Oak Hill city, Tennessee",1600000US4754780,5253,2545,98,208,182,260,5,12,20,51,86,75,186,208,133,276,233,81,73,64,53,67,47,61,66,2708,194,130,120,95,0,152,0,27,204,139,87,209,167,271,267,33,54,84,71,67,47,54780
19,"Oakland town, Tennessee",1600000US4754920,4143,2081,254,239,91,50,5,4,38,37,198,274,189,234,99,76,80,53,35,25,18,72,2,8,0,2062,283,261,75,29,30,7,22,26,222,327,126,124,88,94,118,25,47,18,64,12,47,54920
20,"Oak Ridge city, Tennessee",1600000US4755120,27374,13068,902,768,906,646,268,115,143,515,729,576,856,992,865,978,981,270,473,166,353,447,472,377,270,14306,783,717,837,635,286,221,123,422,479,521,894,1020,1176,1144,1068,348,415,333,263,663,47,55120
21,"Obion town, Tennessee",1600000US4755240,1284,637,58,22,54,18,4,26,37,26,43,68,12,54,23,16,49,15,43,13,7,25,3,15,6,647,62,78,34,13,7,11,0,38,37,34,21,62,28,47,42,10,28,3,13,19,47,55240
22,"Oliver Springs town, Tennessee",1600000US4755800,3213,1341,99,79,101,156,0,38,0,0,211,24,91,153,87,60,44,47,26,0,24,70,13,18,0,1872,77,103,194,110,7,0,50,11,123,118,134,198,119,85,92,27,49,25,91,49,47,55800
23,"Oneida town, Tennessee",1600000US4755860,3822,1886,135,91,147,39,48,42,33,68,111,72,93,179,141,67,159,89,37,44,88,95,51,12,45,1936,96,136,144,35,39,47,47,73,98,159,114,73,144,129,63,0,114,14,17,203,47,55860
24,"Ooltewah CDP, Tennessee",1600000US4755900,4641,2402,112,232,125,81,85,29,0,33,104,244,135,118,254,187,146,39,171,38,25,61,104,48,31,2239,192,78,70,49,28,0,0,54,193,152,152,167,152,201,199,118,95,47,62,73,47,55900
25,"Orlinda city, Tennessee",1600000US4756020,861,434,54,32,22,31,12,2,0,0,63,36,17,31,28,21,18,2,0,13,14,4,14,6,14,427,43,9,58,9,0,8,4,22,58,22,21,38,18,26,3,3,5,27,21,4,47,56020
26,"Orme town, Tennessee",1600000US4756040,92,35,0,0,2,0,0,0,0,0,3,7,3,0,7,4,3,0,2,2,2,0,0,0,0,57,0,0,0,0,0,0,0,0,11,0,0,5,9,3,6,2,4,0,2,0,47,56040
27,"Palmer town, Tennessee",1600000US4756560,805,394,8,27,28,43,0,9,0,0,6,21,22,71,32,43,35,4,2,4,3,16,16,4,0,411,57,18,14,19,7,18,0,6,30,10,52,15,33,20,26,0,7,14,11,25,47,56560
28,"Paris city, Tennessee",1600000US4756720,9863,4473,249,408,231,183,67,120,15,177,227,265,276,441,218,218,283,162,90,46,114,227,128,254,74,5390,296,292,347,202,120,0,60,234,366,216,419,265,352,325,347,76,99,163,104,225,47,56720
29,"Parkers Crossroads city, Tennessee",1600000US4756870,269,128,0,7,7,14,2,0,2,0,20,13,22,2,11,3,3,1,9,3,0,0,7,1,1,141,20,14,6,3,3,2,0,7,12,12,7,5,6,8,11,7,5,2,0,2,47,56870
30,"Parrottsville town, Tennessee",1600000US4757040,137,70,3,6,4,12,2,0,0,3,4,6,5,2,5,7,0,0,0,0,5,2,2,2,0,67,3,8,3,0,0,3,0,0,10,4,0,4,3,2,0,0,2,2,3,3,47,57040
31,"Parsons city, Tennessee",1600000US4757080,2940,1380,152,95,104,78,7,24,18,92,80,139,63,32,107,100,89,8,46,13,10,14,40,24,45,1560,26,0,43,105,64,69,11,116,71,62,93,108,130,66,169,43,50,30,36,29,47,57080
32,"Pegram town, Tennessee",1600000US4757480,2436,1290,42,121,108,77,14,11,21,67,42,35,69,159,142,113,94,23,6,12,21,42,21,40,10,1146,48,58,80,34,54,0,9,18,27,24,79,140,182,163,49,8,29,18,17,55,47,57480
33,"Petersburg town, Tennessee",1600000US4757740,760,360,43,12,19,8,23,3,15,7,51,30,15,20,18,13,38,10,2,0,4,11,6,7,5,400,33,47,32,4,9,9,10,10,29,18,26,42,20,21,8,12,7,9,4,19,47,57740
34,"Philadelphia city, Tennessee",1600000US4757900,474,241,14,11,23,16,0,0,2,4,6,11,3,3,12,27,21,53,4,7,3,0,13,2,6,233,4,15,23,6,10,0,8,4,9,11,5,33,33,9,13,0,9,7,5,4,47,57900
35,"Pigeon Forge city, Tennessee",1600000US4758080,6238,3030,344,238,321,48,52,14,0,13,0,217,140,315,291,61,302,24,39,57,118,93,215,92,36,3208,91,279,333,50,40,33,14,24,237,252,325,216,180,247,158,69,68,113,89,163,47,58080
36,"Pikeville city, Tennessee",1600000US4758120,1507,773,18,26,49,43,44,22,38,50,30,47,49,48,58,74,28,2,32,16,44,28,15,12,0,734,22,39,28,53,5,3,4,19,31,19,70,65,96,58,40,37,28,19,24,31,47,58120
37,"Pine Crest CDP, Tennessee",1600000US4758240,2295,1129,47,41,29,93,38,0,0,29,30,171,99,64,44,92,97,19,35,40,9,74,47,23,8,1166,83,79,29,17,32,0,0,34,83,88,88,54,102,56,106,59,27,0,81,44,47,58240
38,"Piperton city, Tennessee",1600000US4758840,1419,616,14,62,23,20,13,19,0,10,24,12,67,52,74,45,46,4,17,22,39,11,25,6,11,803,19,40,40,50,8,0,0,14,44,5,74,96,83,63,81,10,29,25,21,55,47,58840
39,"Pittman Center town, Tennessee",1600000US4758940,411,204,7,17,20,8,5,0,0,5,7,17,2,3,22,32,29,0,16,0,3,3,8,0,0,207,2,6,18,6,8,0,0,6,9,13,4,4,29,12,36,2,18,2,0,5,47,58940
40,"Plainview city, Tennessee",1600000US4759020,2375,1145,136,81,75,42,14,23,0,50,95,72,60,87,69,92,81,31,22,5,18,53,15,13,11,1230,123,105,74,26,37,24,0,49,77,98,62,164,51,75,85,10,44,17,34,33,47,59020
41,"Pleasant Hill town, Tennessee",1600000US4759240,455,152,4,8,23,5,0,0,0,11,11,10,14,0,7,12,4,6,0,0,0,3,16,18,0,303,19,22,4,0,2,0,8,3,23,8,4,4,14,16,39,0,7,0,15,16,47,59240
42,"Pleasant View city, Tennessee",1600000US4759560,3836,1857,124,138,142,118,37,23,0,85,39,180,186,124,161,143,111,36,47,21,29,30,28,33,22,1979,134,120,159,144,41,9,15,60,114,108,153,147,197,186,82,63,45,18,34,51,47,59560
43,"Portland city, Tennessee",1600000US4760280,10868,5290,546,487,498,229,156,12,115,129,213,463,487,424,354,245,251,85,154,54,75,168,91,33,21,5578,437,264,489,278,123,73,85,123,445,519,370,330,424,430,223,48,255,152,126,178,47,60280
44,"Powells Crossroads town, Tennessee",1600000US4760500,1265,582,81,29,21,39,12,12,0,29,40,32,49,27,28,24,37,11,39,13,11,23,8,10,7,683,53,55,48,31,14,5,3,19,60,37,32,30,58,34,56,13,32,9,10,33,47,60500
45,"Pulaski city, Tennessee",1600000US4761040,7877,3751,215,321,209,130,172,80,31,256,230,87,147,257,206,417,246,125,130,89,76,72,89,58,108,4126,218,75,213,122,111,99,95,87,141,298,212,162,325,339,263,213,116,74,288,146,47,61040
46,"Puryear city, Tennessee",1600000US4761160,722,348,18,24,33,23,0,6,0,0,69,20,4,15,42,7,29,4,10,7,5,13,5,10,4,374,66,17,11,7,0,27,0,16,23,30,29,9,17,19,34,6,14,3,14,17,47,61160
47,"Ramer city, Tennessee",1600000US4761520,300,138,9,13,9,3,4,4,0,0,8,9,17,8,11,0,6,0,6,8,4,0,4,8,7,162,11,13,6,8,10,0,0,0,8,9,14,3,12,10,6,3,11,10,3,5,47,61520
48,"Red Bank city, Tennessee",1600000US4761960,11744,5875,581,303,597,167,87,54,89,261,587,491,423,282,471,335,258,149,93,101,85,169,135,143,14,5869,380,343,283,234,110,52,36,297,636,421,360,357,334,444,439,70,93,77,118,328,47,61960
49,"Red Boiling Springs city, Tennessee",1600000US4762000,1413,586,46,44,11,24,26,0,0,20,20,54,58,32,30,49,47,5,18,11,13,28,21,16,13,827,41,37,24,38,4,0,7,24,47,37,29,34,28,71,47,8,27,19,22,65,47,62000
50,"Ridgely town, Tennessee",1600000US4763060,2060,848,47,49,75,78,16,5,0,8,48,35,115,94,109,38,28,14,17,19,17,7,14,15,0,1212,64,35,109,41,33,2,24,51,93,65,143,120,41,80,63,23,23,18,40,68,47,63060
51,"Ridgeside city, Tennessee",1600000US4763080,503,245,9,16,28,2,4,8,5,18,12,6,11,8,26,12,15,4,26,9,5,9,0,6,6,258,9,7,22,17,3,0,0,0,20,7,22,8,21,7,39,10,17,7,6,8,47,63080
52,"Ridgetop city, Tennessee",1600000US4763140,1725,837,42,32,83,36,22,8,9,43,27,44,61,46,47,118,44,19,31,28,18,43,22,14,0,888,42,54,42,25,35,0,7,31,52,39,67,87,59,72,59,24,44,14,41,45,47,63140
53,"Ripley city, Tennessee",1600000US4763340,7608,3586,406,318,335,118,164,17,66,188,209,259,185,208,255,251,174,29,97,46,35,110,52,15,49,4022,345,284,298,225,74,40,49,194,274,139,250,309,273,251,218,41,154,38,37,178,47,63340
54,"Rives town, Tennessee",1600000US4763800,365,183,20,12,12,4,5,2,0,7,32,0,10,8,11,3,20,0,3,0,3,16,3,7,5,182,6,30,6,4,4,15,0,3,2,19,9,6,13,12,14,0,4,0,1,16,47,63800
55,"Roan Mountain CDP, Tennessee",1600000US4763840,1002,538,15,32,47,16,24,0,0,0,42,11,59,87,15,60,56,13,19,0,0,12,21,0,9,464,0,0,18,46,21,16,0,0,61,0,43,31,54,32,45,0,6,8,31,23,47,63840
56,"Rockford city, Tennessee",1600000US4764160,1024,533,21,44,35,27,6,8,11,28,20,15,20,45,55,55,33,12,22,12,18,15,10,12,9,491,17,19,35,17,3,0,0,40,30,40,24,37,26,49,52,15,6,19,3,26,47,64160
57,"Rockwood city, Tennessee",1600000US4764440,5475,2269,118,143,126,105,62,15,23,70,67,140,150,177,188,168,194,78,90,91,91,55,47,10,61,3206,89,361,119,129,51,35,36,99,163,133,134,209,326,145,212,122,175,43,94,252,47,64440
58,"Rogersville town, Tennessee",1600000US4764820,4291,1964,141,183,130,72,132,0,21,54,137,131,149,86,106,70,55,74,68,15,60,78,56,100,46,2327,137,126,172,55,6,16,0,64,130,89,245,108,144,80,112,37,89,54,88,106,47,64820
59,"Rossville town, Tennessee",1600000US4765240,617,309,7,23,29,14,3,2,0,19,22,19,27,29,25,19,24,0,10,9,7,0,17,4,0,308,11,20,6,11,2,0,0,6,26,6,37,54,20,19,17,14,12,14,3,9,47,65240
60,"Rural Hill CDP, Tennessee",1600000US4765642,2054,1142,99,42,182,16,43,0,0,16,0,54,114,86,79,147,62,0,77,20,29,32,28,0,16,912,72,0,53,26,30,21,15,49,20,55,71,94,18,201,31,15,100,9,0,18,47,65642
61,"Rutherford town, Tennessee",1600000US4765760,1194,518,36,26,51,22,15,9,6,29,5,7,54,51,47,33,19,7,16,11,9,30,19,12,4,676,36,31,55,40,7,0,15,26,26,28,35,79,61,30,23,11,13,10,31,31,47,65760
62,"Rutledge town, Tennessee",1600000US4765820,1103,538,44,69,20,9,35,17,0,18,35,39,40,39,48,8,25,29,39,5,19,0,0,0,0,565,61,36,62,7,27,7,0,29,24,80,61,20,15,19,9,18,15,44,8,14,47,65820
63,"St. Joseph city, Tennessee",1600000US4766160,690,360,25,24,36,25,8,0,0,6,29,17,29,41,23,20,20,5,6,10,12,10,9,5,0,330,33,12,26,13,14,0,5,2,21,12,23,25,22,37,10,6,9,8,9,6,47,66160
64,"Saltillo town, Tennessee",1600000US4766340,379,170,7,0,0,9,7,13,0,10,16,7,3,22,8,21,5,4,4,4,8,8,4,8,2,209,10,0,2,8,17,11,0,17,33,0,15,10,10,18,4,15,5,8,4,6,47,66340
65,"Samburg town, Tennessee",1600000US4766360,327,188,8,0,0,2,23,8,4,11,23,12,9,14,3,10,23,9,3,1,5,12,4,2,2,139,7,7,0,9,0,0,0,0,15,3,8,8,9,12,9,7,17,3,7,3,47,66360
66,"Sardis town, Tennessee",1600000US4766660,455,220,22,11,19,9,0,0,3,8,11,0,24,24,19,28,8,2,7,5,9,5,5,1,0,235,13,20,2,5,12,0,3,3,4,22,17,13,14,24,8,7,21,4,7,22,47,66660
67,"Saulsbury town, Tennessee",1600000US4766680,44,16,0,0,2,0,0,0,0,1,0,0,0,1,0,3,3,0,2,2,0,0,0,2,0,28,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,3,3,0,1,0,47,66680
68,"Savannah city, Tennessee",1600000US4766720,7245,3204,168,378,295,79,79,3,7,190,300,266,113,215,145,151,109,31,125,23,201,100,33,110,83,4041,223,293,163,195,103,34,127,73,347,213,249,208,185,222,235,80,188,59,119,192,47,66720
69,"Scotts Hill town, Tennessee",1600000US4766880,873,385,15,23,39,21,7,3,0,6,6,25,22,23,7,56,38,0,5,10,12,21,13,13,20,488,15,16,22,30,12,3,0,11,22,23,21,20,31,43,31,27,24,6,23,34,47,66880
70,"Selmer town, Tennessee",1600000US4766940,4630,2186,216,167,108,83,74,38,31,66,76,83,180,245,207,102,147,56,28,31,51,12,92,59,34,2444,33,189,121,151,57,0,0,105,153,154,225,153,136,172,122,47,157,53,16,47,47,66940
71,"Sevierville city, Tennessee",1600000US4767120,16398,7976,690,563,314,204,187,135,83,530,905,468,695,554,462,405,420,254,177,156,237,118,123,179,117,8422,664,329,503,150,92,64,227,431,693,360,644,481,352,644,750,102,245,291,281,326,47,67120
72,"Sewanee CDP, Tennessee",1600000US4767140,2399,1119,54,61,13,19,229,110,144,4,63,29,73,24,25,47,39,45,10,0,24,34,56,16,0,1280,19,117,9,14,322,88,160,123,22,12,31,94,56,42,19,40,9,21,31,0,47,67140
73,"Seymour CDP, Tennessee",1600000US4767200,9740,4957,348,357,364,411,178,60,144,95,291,319,381,326,379,360,310,95,97,21,70,164,35,85,67,4783,266,325,238,195,174,45,58,109,277,267,345,427,494,222,253,174,109,113,87,150,47,67200
74,"Sharon town, Tennessee",1600000US4767540,1089,454,21,40,33,8,4,9,0,25,27,24,41,72,15,25,24,10,6,5,12,20,23,4,6,635,32,48,39,47,18,0,13,27,15,49,15,56,46,25,31,9,29,17,11,21,47,67540
75,"Shelbyville city, Tennessee",1600000US4767760,19478,9401,968,907,479,395,339,213,147,337,848,768,654,589,584,574,393,127,95,105,53,340,179,199,108,10077,944,912,456,336,121,145,191,443,938,711,510,727,589,497,503,191,119,96,145,491,47,67760
76,"Signal Mountain town, Tennessee",1600000US4768540,7236,3219,222,234,324,78,96,0,0,142,84,62,227,235,273,273,230,133,82,75,54,138,70,106,81,4017,176,272,385,207,36,19,44,0,125,188,249,315,255,226,313,114,105,46,37,130,47,68540
77,"Silerton town, Tennessee",1600000US4768560,65,30,0,0,0,4,0,0,0,2,0,0,0,6,3,11,0,0,0,2,0,0,2,0,0,35,0,0,2,0,0,0,0,0,0,0,2,17,3,0,0,0,3,0,2,2,47,68560
78,"Slayden town, Tennessee",1600000US4769080,297,134,8,13,0,0,2,0,0,5,21,3,2,0,13,6,13,17,0,7,2,3,19,0,0,163,28,15,6,0,3,0,0,0,21,3,3,15,9,7,6,2,6,0,4,7,47,69080
79,"Smithville city, Tennessee",1600000US4769320,4304,1931,149,95,132,84,69,35,29,62,147,257,159,177,130,73,84,0,22,53,14,27,73,24,36,2373,217,109,167,123,48,8,0,43,147,141,71,249,146,136,133,62,153,42,78,98,47,69320
80,"Smyrna town, Tennessee",1600000US4769420,36921,17726,1782,1343,1186,523,271,344,192,581,1936,1680,1287,1285,1283,1102,905,324,393,165,272,340,362,75,95,19195,1527,1402,1339,896,381,105,308,650,1905,1700,1221,1330,1539,1136,862,495,458,244,360,335,47,69420
81,"Sneedville town, Tennessee",1600000US4769460,1658,809,92,40,28,16,20,6,10,31,121,61,64,46,62,44,37,8,0,25,6,21,35,18,18,849,46,97,58,22,16,28,0,7,67,28,67,22,89,31,47,3,16,12,35,53,47,69460
82,"Soddy-Daisy city, Tennessee",1600000US4769560,12486,6116,310,277,324,290,137,39,101,269,559,262,411,422,510,494,460,246,228,96,217,154,205,67,38,6370,448,496,254,164,138,28,43,203,436,314,470,270,670,552,458,190,151,162,288,221,47,69560
83,"Somerville town, Tennessee",1600000US4769620,2914,1546,141,131,89,47,5,34,56,66,126,129,62,160,136,58,27,58,52,23,9,30,38,15,54,1368,132,76,72,50,39,9,0,37,97,120,95,32,84,55,75,52,37,50,27,43,47,69620
84,"South Carthage town, Tennessee",1600000US4769680,1562,674,61,50,96,32,0,0,4,17,29,44,59,47,38,27,35,21,15,18,16,27,15,18,5,888,65,81,45,58,4,8,11,60,50,95,59,66,56,35,33,11,26,19,16,34,47,69680
85,"South Cleveland CDP, Tennessee",1600000US4769740,5870,3054,322,255,253,115,23,35,81,108,189,173,198,376,159,177,219,43,70,21,59,85,43,24,26,2816,168,166,122,101,30,12,34,119,234,170,185,174,198,150,321,82,128,85,79,125,47,69740
86,"South Fulton city, Tennessee",1600000US4769900,2075,907,34,55,100,44,29,0,0,28,23,86,72,81,78,44,40,24,50,22,26,17,17,12,25,1168,72,40,88,42,3,0,0,65,71,96,111,45,66,48,76,67,35,19,55,28,47,69900
87,"South Pittsburg city, Tennessee",1600000US4770060,3113,1275,65,54,112,21,49,0,26,23,64,53,161,69,37,134,82,86,37,26,47,34,32,47,16,1838,151,130,51,33,86,8,13,89,81,72,147,31,124,138,109,108,55,31,45,90,47,70060
88,"Sparta city, Tennessee",1600000US4770180,4872,2097,274,86,118,130,68,54,21,65,137,89,72,127,228,119,92,19,96,24,55,104,87,26,6,2775,190,172,91,108,47,40,41,60,179,172,142,118,210,287,155,105,61,59,52,166,47,70180
89,"Spencer town, Tennessee",1600000US4770240,2102,1062,74,101,77,42,48,0,26,20,52,80,49,56,50,125,56,35,37,6,12,40,46,25,5,1040,72,82,29,32,62,17,19,40,42,54,56,68,86,90,57,12,38,8,60,61,47,70240
90,"Spring City town, Tennessee",1600000US4770400,2166,1114,102,62,47,40,34,13,12,37,114,54,28,49,34,129,91,55,37,14,6,58,49,30,19,1052,31,39,19,20,25,27,43,20,93,27,45,62,94,45,90,8,48,17,61,40,47,70400
91,"Springfield city, Tennessee",1600000US4770500,16817,8556,1105,673,567,220,230,95,56,466,721,647,606,754,565,365,460,65,141,77,153,187,164,167,72,8261,909,600,449,141,146,126,77,246,901,586,461,568,420,486,566,103,190,137,242,226,47,70500
92,"Spring Hill city, Tennessee",1600000US4770580,22993,11137,1256,1275,1118,376,187,226,83,186,821,883,1154,843,817,702,292,199,87,154,77,179,143,64,15,11856,1398,1069,780,380,321,146,76,223,926,1052,1304,962,762,691,439,217,304,83,130,263,47,70580
93,"Spurgeon CDP, Tennessee",1600000US4770680,3423,1452,67,68,63,74,29,0,23,20,181,125,73,100,99,137,103,57,20,28,52,85,24,14,10,1971,231,76,83,28,0,0,23,49,269,119,119,153,144,110,157,43,71,81,58,52,47,70680
94,"Stanton town, Tennessee",1600000US4770820,504,172,0,24,10,5,0,7,0,8,33,0,0,20,25,4,2,0,2,0,11,9,4,4,4,332,17,25,21,5,6,0,0,0,47,25,0,55,44,16,23,4,7,10,3,0,47,70820

## Places Needed:  
### Per County:  
+ Cheatham County: Ashland City town, Kingston Springs town, Pegram town, Pleasant View city  
+ Davidson County: Belle Meade city, Berry Hill city, Forest Hills city, **Goodlettsville** city, 
Nashville-Davidson metropolitan government (balance), Oak Hill city, **Ridgetop** city  
+ Dickson County: Burns town, Charlotte town, Dickson city, Slayden town, Vanleer town, White Bluff town  
+ Houston County: Erin city, **Tennessee Ridge** town  
+ Humphreys County: McEwen city, New Johnsonville city, Waverly city  
+ Maury County: Columbia city, Mount Pleasant city, **Spring Hill** city  
+ Montgomery County: Clarksville city  
+ Robertson County: Adams city, Cedar Hill city, Coopertown town, Cross Plains city, Greenbrier town, **Millersville** city, **Portland** city, **Ridgetop** city, Springfield city, **White House** city  
+ Rutherford County: Eagleville city, La Vergne city, Murfreesboro city, Smyrna town
+ Stewart County: Cumberland City town, Dover city, **Tennessee Ridge** town  
+ Sumner County: Gallatin city, **Goodlettsville** city, Hendersonville city, **Millersville** city, **Portland** city, Westmoreland town, **White House** city  
+ Trousdale County: Hartsville  
+ Williamson County: Brentwood city, Fairview city, Franklin city, Nolensville town, **Spring Hill** city, Thompson's Station town  
+ Wilson County: Lebanon city, Mount Juliet city, Watertown city  

So the ones without overlapping places are: Cheatham, Dickson, Humphreys, Montgomery, Rutherford, Trousdale, and Wilson Counties

In [217]:
lakewood = places.loc[places['NAME'] == "Nashville-Davidson metropolitan government (balance), Tennessee"]
lakewood

,NAME,GEO_ID,agebysex_total_series,age_total_male,age_m_u5,age_m_5to9,age_m_10to14,age_m_15to17,age_m_18to19,age_m_20,age_m_21,age_m_22to24,age_m_25to29,age_m_30to34,age_m_35to39,age_m_40to44,age_m_45to49,age_m_50to54,age_m_55to59,age_m_60to61,age_m_62to64,age_m_65to66,age_m_67to69,age_m_70to74,age_m_75to79,age_m_80to84,age_m_85+,age_total_female,age_f_u5,age_f_5to9,age_f_10to14,age_f_15to17,age_f_18to19,age_f_20,age_f_21,age_f_22to24,age_f_25to29,age_f_30to34,age_f_35to39,age_f_40to44,age_f_45to49,age_f_50to54,age_f_55to59,age_f_60to61,age_f_62to64,age_f_65to66,age_f_67to69,age_f_70to74,StateFIPS,GeoFIPS
5,Nashville-Davidson metropolitan government (ba...,1600000US4752006,592497,287475,22375,17907,16503,9783,8564,4744,4641,13540,29985,25245,22516,20956,20648,18703,15587,5446,5966,3451,4167,6065,5002,3242,2439,305022,21743,17637,16036,9641,8742,3955,4714,14374,30096,25711,20807,21214,21277,20031,18004,5550,7112,4033,5236,8654,47,52006

In [214]:
places = ['1600000US4702180', #Ashland City: Cheatham
          '1600000US4739660', #Kingston Springs: Cheatham
          '1600000US4757480', #Pegram: Cheatham
          '1600000US4759560', #Pleasant View: Cheatham
          '1600000US4704620', #Belle Meade: Davidson
          '1600000US4705140', #Berry Hill: Davidson
          '1600000US4727020', #Forest Hills: Davidson
          '1600000US4729920', #Goodlettsville: Davidson/Sumner
          '1600000US4752006', #Nashville-Davidson metropolitan government (balance): Davidson
          '1600000US4754780', #Oak Hill: Davidson
          '1600000US4763140', #Ridgetop: Davidson/Robertson
          '1600000US4709880', #Burns: Dickson
          '1600000US4713080', #Charlotte: Dickson
          '1600000US4720620', #Dickson: Dickson
          '1600000US4769080', #Slayden: Dickson
          '1600000US4776860', #Vanleer: Dickson
          '1600000US4779980', #White Bluff: Dickson
          '1600000US4724320', #Erin: Houston
          '1600000US4773460', #Tennessee Ridge: Houston/Stewart
          '1600000US4744840', #McEwen: Humphreys
          '1600000US4752820', #New Johnsonville: Humphreys
          '1600000US4778560', #Waverly: Humphreys
          '1600000US4716540', #Columbia: Maury
          '1600000US4751080', #Mount Pleasant: Maury
          '1600000US4770580', #Spring Hill: Maury/Williamson
          '1600000US4715160', #Clarksville: Montgomery
          '1600000US4700200', #Adams: Robertson
          '1600000US4711980', #Cedar Hill: Robertson
          '1600000US4716980', #Coopertown: Robertson
          '1600000US4718420', #Cross Plains: Robertson
          '1600000US4730960', #Greenbrier: Robertson
          '1600000US4748980', #Millersville: Robertson/Sumner
          '1600000US4760280', #Portland: Robertson/Sumner
          '1600000US4770500', #Springfield: Robertson
          '1600000US4780200', #White House: Robertson/Sumner
          '1600000US4722360', #Eagleville: Rutherford
          '1600000US4741200', #La Vergne: Rutherford
          '1600000US4751560', #Murfreesboro: Rutherford
          '1600000US4769420', #Smyrna: Rutherford
          '1600000US4718820', #Cumberland City: Stewart
          '1600000US4721400', #Dover: Stewart
          '1600000US4728540', #Gallatin: Sumner
          '1600000US4733280', #Hendersonville: Sumner
          '1600000US4779420', #Westmoreland: Sumner
          '1600000US4708280', #Brentwood: Williamson
          '1600000US4725440', #Fairview: Williamson
          '1600000US4727740', #Franklin: Williamson
          '1600000US4753460', #Nolensville: Williamson
          '1600000US4773900', #Thompson's Station: Williamson
          '1600000US4741520', #Lebanon: Wilson
          '1600000US4750780', #Mount Juliet: Wilson
          '1600000US4778320'] #Watertown: Wilson

In [37]:
test=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')

In [39]:
# ONE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg1['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg1['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
one = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
one = one.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
one = one.append(state, ignore_index = True)
onepull = one
print('Okay Finished')

Okay Finished

In [40]:
#placemarker
one = onepull

In [41]:
# TWO
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg2['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg2['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
two = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
two = two.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
two = two.append(state, ignore_index = True)
twopull = two
print('Okay Finished')

Okay Finished

In [42]:
two = twopull

In [43]:
# THREE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg3['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg3['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
three = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
three = three.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
three = three.append(state, ignore_index = True)
threepull = three
print('Okay Finished')

Okay Finished

In [44]:
three = threepull

In [45]:
# FOUR
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg4['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg4['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
four = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
four = four.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
four = four.append(state, ignore_index = True)
fourpull = four
print('Okay Finished')

Okay Finished

In [46]:
four = fourpull

In [47]:
# FIVE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg5['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg5['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
five = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
five = five.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
five = five.append(state, ignore_index = True)
fivepull = five
print('Okay Finished')

Okay Finished

In [48]:
five = fivepull

In [49]:
# SIX
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg6['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg6['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
six = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
six = six.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
six = six.append(state, ignore_index = True)
sixpull = six
print('Okay Finished')

Okay Finished

In [50]:
six = sixpull

In [51]:
# SEVEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg7['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg7['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
seven = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
seven = seven.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
seven = seven.append(state, ignore_index = True)
sevenpull = seven
print('Okay Finished')

Okay Finished

In [52]:
seven = sevenpull

In [53]:
# EIGHT
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg8['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg8['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
eight = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
eight = eight.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
eight = eight.append(state, ignore_index = True)
eightpull = eight
print('Okay Finished')

Okay Finished

In [54]:
eight = eightpull

In [55]:
# NINE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg9['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg9['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
nine = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
nine = nine.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
nine = nine.append(state, ignore_index = True)
ninepull = nine
print('Okay Finished')

Okay Finished

In [56]:
nine = ninepull

In [57]:
# TEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg10['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg10['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
ten = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
ten = ten.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
ten = ten.append(state, ignore_index = True)
tenpull = ten
print('Okay Finished')

Okay Finished

In [58]:
ten = tenpull

In [59]:
# ELEVEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg11['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg11['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
eleven = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
eleven = eleven.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
eleven = eleven.append(state, ignore_index = True)
elevenpull = eleven
print('Okay Finished')

Okay Finished

In [61]:
eleven = elevenpull

In [62]:
# Twelve
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg12['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg12['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twelve = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twelve = twelve.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twelve = twelve.append(state, ignore_index = True)
twelvepull = twelve
print('Okay Finished')

Okay Finished

In [63]:
twelve = twelvepull

In [64]:
# Thirteen
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg13['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg13['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
thirteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
thirteen = thirteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
thirteen = thirteen.append(state, ignore_index = True)
thirteenpull = thirteen
print('Okay Finished')

Okay Finished

In [65]:
thirteen = thirteenpull

In [66]:
# FOURTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg14['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg14['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
fourteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
fourteen = fourteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
fourteen = fourteen.append(state, ignore_index = True)
fourteenpull = fourteen
print('Okay Finished')

Okay Finished

In [67]:
fourteen = fourteenpull

In [68]:
# FIFTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg15['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg15['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
fifteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
fifteen = fifteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
fifteen = fifteen.append(state, ignore_index = True)
fifteenpull = fifteen
print('Okay Finished')

Okay Finished

In [69]:
fifteen = fifteenpull

In [70]:
# SIXTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg16['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg16['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
sixteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
sixteen = sixteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
sixteen = sixteen.append(state, ignore_index= True)
sixteenpull = sixteen
print('Okay Finished')

Okay Finished

In [71]:
sixteen = sixteenpull

In [72]:
# SEVENTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg17['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg17['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
seventeen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
seventeen = seventeen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
seventeen = seventeen.append(state, ignore_index= True)
seventeenpull = seventeen
print('Okay Finished')

Okay Finished

In [73]:
seventeen = seventeenpull

In [74]:
# EIGHTEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg18['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg18['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
eighteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
eighteen = eighteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
eighteen = eighteen.append(state, ignore_index= True)
eighteenpull = eighteen
print('Okay Finished')

Okay Finished

In [75]:
eighteen = eighteenpull

In [76]:
# NINETEEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg19['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg19['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
nineteen = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
nineteen = nineteen.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
nineteen = nineteen.append(state, ignore_index= True)
nineteenpull = nineteen
print('Okay Finished')

Okay Finished

In [77]:
nineteen = nineteenpull

In [78]:
# TWENTY
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg20['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg20['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twenty = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twenty = twenty.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twenty = twenty.append(state, ignore_index= True)
twentypull = twenty
print('Okay Finished')

Okay Finished

In [79]:
twenty = twentypull

In [80]:
# TWENTYONE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg21['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg21['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentyone = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentyone = twentyone.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentyone = twentyone.append(state, ignore_index= True)
twentyonepull = twentyone
print('Okay Finished')

Okay Finished

In [81]:
twentyone = twentyonepull

In [82]:
# TWENTYTWO
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg22['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg22['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentytwo = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentytwo = twentytwo.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentytwo = twentytwo.append(state, ignore_index= True)
twentytwopull = twentytwo
print('Okay Finished')

Okay Finished

In [83]:
twentytwo = twentytwopull

In [84]:
# TWENTYTHREE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg23['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg23['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentythree = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentythree = twentythree.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentythree = twentythree.append(state, ignore_index= True)
twentythreepull = twentythree
print('Okay Finished')

Okay Finished

In [85]:
twentythree = twentythreepull

In [86]:
# TWENTYFOUR
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg24['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg24['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentyfour = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentyfour = twentyfour.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentyfour = twentyfour.append(state, ignore_index= True)
twentyfourpull = twentyfour
print('Okay Finished')

Okay Finished

In [87]:
twentyfour = twentyfourpull

In [88]:
# TWENTYFIVE
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg25['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg25['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentyfive = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentyfive = twentyfive.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentyfive = twentyfive.append(state, ignore_index= True)
twentyfivepull = twentyfive
print('Okay Finished')

Okay Finished

In [89]:
twentyfive = twentyfivepull

In [90]:
# TWENTYSIX
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg26['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg26['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentysix = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentysix = twentysix.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentysix = twentysix.append(state, ignore_index= True)
twentysixpull = twentysix
print('Okay Finished')

Okay Finished

In [91]:
twentysix = twentysixpull

In [92]:
# TWENTYSEVEN
# listparams
head1 = 'NAME'
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'GeoFIPS'
#make variables list
var_list = list(dg27['ACS Variable'])
#add stuff to variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
var_list = list(var_list)
#make columns list
col_list = list(dg27['Column Name'])
#add stuff to columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
col_list = list(col_list)
#add stuff to columns list
data_appended = []
for i in GNRC:
    url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
    predicates= {}
    get_vars= var_list
    predicates["get"]= ",". join(get_vars)
    predicates["for"]= "county:{}".format(i)
    predicates["in"]= "state:47"
    data= requests.get(url_str, params= predicates)
    col_names = col_list
    data=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
    data_appended.append(data)
data_appended = pd.concat(data_appended).reset_index(drop = True)
twentyseven = data_appended
#places call
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "place:*"
predicates["in"]= "state:47"
data= requests.get(url_str, params= predicates)
col_names = col_list
places=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
places=places.loc[(places['GEO_ID']=='1600000US4722360')|(places['GEO_ID']=='1600000US4751560')|(places['GEO_ID']=='1600000US4741200')
                |(places['GEO_ID']=='1600000US4769420')|(places['GEO_ID']=='1600000US4778320')|(places['GEO_ID']=='1600000US4750780')
                |(places['GEO_ID']=='1600000US4741520')|(places['GEO_ID']=='1600000US4702180')|(places['GEO_ID']=='1600000US4702180')
                |(places['GEO_ID']=='1600000US4739660')|(places['GEO_ID']=='1600000US4757480')|(places['GEO_ID']=='1600000US4759560')
                |(places['GEO_ID']=='1600000US4709880')|(places['GEO_ID']=='1600000US4713080')|(places['GEO_ID']=='1600000US4720620')
                |(places['GEO_ID']=='1600000US4769080')|(places['GEO_ID']=='1600000US4776860')|(places['GEO_ID']=='1600000US4779980')
                |(places['GEO_ID']=='1600000US4744840')|(places['GEO_ID']=='1600000US4752820')|(places['GEO_ID']=='1600000US4778560')
                |(places['GEO_ID']=='1600000US4715160')|(places['GEO_ID']=='1600000US4732742')|(places['GEO_ID']=='1600000US4728540')]
twentyseven = twentyseven.append(places).reset_index(drop = True)
#state call
col_list.remove(tail_cols2)
url_str= 'https://api.census.gov/data/2020/acs/acs5?key='+api_key
predicates= {}
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "state:47".format(i)
data= requests.get(url_str, params= predicates)
col_names = col_list
state=pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
state['GeoFIPS'] = '0'
twentyseven = twentyseven.append(state, ignore_index= True)
twentysevenpull = twentyseven
print('Okay Finished')

Okay Finished

In [93]:
twentyseven = twentysevenpull

In [94]:
last = twentyseven

In [139]:
last.tail()

,GEO_ID,traveltimemode_taximotorcyclebicycleorother_45to59,traveltimemode_taximotorcyclebicycleorother_60ormore,fb_total_series,fb_nativeborn,fb_foreignborn,fb_foreignborn_naturalizeduscitizen,fb_foreignborn_notauscitizen,disability_agebynumber_series_total,disability_u18_total,disability_u18_1disability,disability_u18_2ormoredisabilities,disability_u18_nodisability,disability_18to64_total,disability_18to64_1disability,disability_18to64_2ormoredisabilities,disability_18to64_nodisability,disability_65+_total,disability_65+_1disability,disability_65+_2ormoredisabilities,disability_65+_nodisability,StateFIPS,GeoFIPS
33,1600000US4776860,0,0,None,None,None,None,None,418,93,1,0,92,300,13,6,281,25,9,4,12,47,76860
34,1600000US4778320,0,0,None,None,None,None,None,1698,439,24,3,412,992,154,82,756,267,62,73,132,47,78320
35,1600000US4778560,0,0,2245,2228,17,0,17,3976,675,86,0,589,2257,174,274,1809,1044,270,234,540,47,78560
36,1600000US4779980,0,0,None,None,None,None,None,3583,705,40,0,665,2446,276,435,1735,432,55,112,265,47,79980
37,0400000US47,1914,4297,3154232,2941235,212997,88651,124346,6664134,1505251,57989,18524,1428738,4079574,285685,252647,3541242,1079309,186133,230689,662487,47,0

In [95]:
dfs = [two,three,four,five,six,seven,eight,nine,ten,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty,twentyone,twentytwo,twentythree,
      twentyfour,twentyfive,twentysix]

In [96]:
for df in dfs:
    df = df.drop(columns = ['NAME','StateFIPS','GeoFIPS'], inplace = True)

In [97]:
one = one.drop(columns = ['StateFIPS','GeoFIPS'])
last = last.drop(columns = 'NAME')

The default inplace=False is intended for assigning back to the original dataframe, because it returns a new copy. However inplace=True operates on the same copy and returns None, therefore there is no need to assign back to the original dataframe.

In [98]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [103]:
#df_merged.tail()

In [101]:
dfs = [one, df_merged, last]
data = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [105]:
data.head()

,NAME,GEO_ID,agebysex_total_series,age_total_male,age_m_u5,age_m_5to9,age_m_10to14,age_m_15to17,age_m_18to19,age_m_20,age_m_21,age_m_22to24,age_m_25to29,age_m_30to34,age_m_35to39,age_m_40to44,age_m_45to49,age_m_50to54,age_m_55to59,age_m_60to61,age_m_62to64,age_m_65to66,age_m_67to69,age_m_70to74,age_m_75to79,age_m_80to84,age_m_85+,age_total_female,age_f_u5,age_f_5to9,age_f_10to14,age_f_15to17,age_f_18to19,age_f_20,age_f_21,age_f_22to24,age_f_25to29,age_f_30to34,age_f_35to39,age_f_40to44,age_f_45to49,age_f_50to54,age_f_55to59,age_f_60to61,age_f_62to64,age_f_65to66,age_f_67to69,age_f_70to74,age_f_75to79,age_f_80to84,age_f_85+,raceeth_white_alone,raceeth_blackafricanamerican_alone,raceeth_americanindianalaskanative_alone,raceeth_asian_alone,raceeth_nativehawaiianotherpacificislander_alone,raceeth_someotherrace_alone,raceeth_twoormoreraces_alone,raceeth_whitealone_nothispanicorlatino,raceeth_hispanicorlatino,hhsize_avg,healthcoverage_total_healthcare_series,healthcoverage_total_mallhealthcare,healthcoverage_mu6_all,healthcoverage_mu6_w,healthcoverage_mu6_wo,healthcoverage_m6to18_all,healthcoverage_m6to18_w,healthcoverage_m6to18_wo,healthcoverage_m19to25_all,healthcoverage_m19to25_w,healthcoverage_m19to25_wo,healthcoverage_m26to34_all,healthcoverage_m26to34_w,healthcoverage_m26to34_wo,healthcoverage_m35to44_all,healthcoverage_m35to44_w,healthcoverage_m35to44_wo,healthcoverage_m45to54_all,healthcoverage_m45to54_w,healthcoverage_m45to54_wo,healthcoverage_m55to64_all,healthcoverage_m55to64_w,healthcoverage_m55to64_wo,healthcoverage_m65to74_all,healthcoverage_m65to74_w,healthcoverage_m65to74_wo,healthcoverage_m75+_all,healthcoverage_m75+_w,healthcoverage_m75+_wo,healthcoverage_total_fallhealthcare,healthcoverage_fu6_all,healthcoverage_fu6_w,healthcoverage_fu6_wo,healthcoverage_f6to18_all,healthcoverage_f6to18_w,healthcoverage_f6to18_wo,healthcoverage_f19to25_all,healthcoverage_f19to25_w,healthcoverage_f19to25_wo,healthcoverage_f26to34_all,healthcoverage_f26to34_w,healthcoverage_f26to34_wo,healthcoverage_f35to44_all,healthcoverage_f35to44_w,healthcoverage_f35to44_wo,healthcoverage_f45to54_all,healthcoverage_f45to54_w,healthcoverage_f45to54_wo,healthcoverage_f55to64_all,healthcoverage_f55to64_w,healthcoverage_f55to64_wo,healthcoverage_f65to74_all,healthcoverage_f65to74_w,healthcoverage_f65to74_wo,healthcoverage_f75+_all,healthcoverage_f75+_w,healthcoverage_f75+_wo,healthcoverage_total_privatehealthcare_series,healthcoverage_total_mprivate,healthcoverage_mu6_privateall,healthcoverage_mu6_wprivate,healthcoverage_mu6_woprivate,healthcoverage_m6to18_privateall,healthcoverage_m6to18_wprivate,healthcoverage_m6to18_woprivate,healthcoverage_m19to25_privateall,healthcoverage_m19to25_wprivate,healthcoverage_m19to25_woprivate,healthcoverage_m26to34_privateall,healthcoverage_m26to34_wprivate,healthcoverage_m26to34_woprivate,healthcoverage_m35to44_privateall,healthcoverage_m35to44_wprivate,healthcoverage_m35to44_woprivate,healthcoverage_m45to54_privateall,healthcoverage_m45to54_wprivate,healthcoverage_m45to54_woprivate,healthcoverage_m55to64_privateall,healthcoverage_m55to64_wprivate,healthcoverage_m55to64_woprivate,healthcoverage_m65to74_privateall,healthcoverage_m65to74_wprivate,healthcoverage_m65to74_woprivate,healthcoverage_m75+_privateall,healthcoverage_m75+_wprivate,healthcoverage_m75+_woprivate,healthcoverage_total_fprivate,healthcoverage_fu6_privateall,healthcoverage_fu6_wprivate,healthcoverage_fu6_woprivate,healthcoverage_f6to18_privateall,healthcoverage_f6to18_wprivate,healthcoverage_f6to18_woprivate,healthcoverage_f19to25_privateall,healthcoverage_f19to25_wprivate,healthcoverage_f19to25_woprivate,healthcoverage_f26to34_privateall,healthcoverage_f26to34_wprivate,healthcoverage_f26to34_woprivate,healthcoverage_f35to44_privateall,healthcoverage_f35to44_wprivate,healthcoverage_f35to44_woprivate,healthcoverage_f45to54_privateall,healthcoverage_f45to54_wprivate,healthcoverage_f45to54_woprivate,healthcoverage_f55to64_privateall,healthcoverage_f55to64_wprivate,healthcoverage_f55to64_woprivate,healthcoverage_f65to74_privateall,healthcoverage_f65to74_wprivate,healthcoverage_f65to74_woprivate,healthcoverage_f75+_privateall,healthcoverage_f75+_wprivate,healthcoverage_f75+_woprivate,healthcoverage_total_publichealthcare_series,healthcoverage_total_mpublic,healthcoverage_mu6_publicall,healthcoverage_mu6_wpublic,healthcoverage_mu6_wopublic,healthcoverage_m6to18_publicall,healthcoverage_m6to18_wpublic,healthcoverage_m6to18_wopublic,healthcoverage_m19to25_publicall,healthcoverage_m19to25_wpublic,healthcoverage_m19to25_wopublic,healthcoverage_m26to34_publicall,healthcoverage_m26to34_wpublic,healthcoverage_m26to34_wopublic,healthcoverage_m35to44_publicall,healthcoverage_m35to44_wpublic,healthcoverage_m35to44_wopublic,healthcoverage_m45to54_publicall,healthcoverage_m45to54_wpublic,healthcoverage_m45to54_wopublic,healthcoverage_m55to64_publicall,healthcoverage_m55to64_wpublic,healthcoverage_m55to64_wopublic,healthcoverage_m65to74_publicall,healthcoverage_m65to74_wpublic,healthcoverage_m65to74_wopublic,healthcoverage_m75+_publicall,healthcoverage_m75+_wpublic,healthcoverage_m75+_wopublic,healthcoverage_total_fpublic,healthcoverage_fu6_publicall,healthcoverage_fu6_wpublic,healthcoverage_fu6_wopublic,healthcoverage_f6to18_publicall,healthcoverage_f6to18_wpublic,healthcoverage_f6to18_wopublic,healthcoverage_f19to25_publicall,healthcoverage_f19to25_wpublic,healthcoverage_f19to25_wopublic,healthcoverage_f26to34_publicall,healthcoverage_f26to34_wpublic,healthcoverage_f26to34_wopublic,healthcoverage_f35to44_publicall,healthcoverage_f35to44_wpublic,healthcoverage_f35to44_wopublic,healthcoverage_f45to54_publicall,healthcoverage_f45to54_wpublic,healthcoverage_f45to54_wopublic,healthcoverage_f55to64_publicall,healthcoverage_f55to64_wpublic,healthcoverage_f55to64_wopublic,healthcoverage_f65to74_publicall,healthcoverage_f65to74_wpublic,healthcoverage_f65to74_wopublic,healthcoverage_f75+_publicall,healthcoverage_f75+_wpublic,healthcoverage_f75+_wopublic,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,hhincome_total_series,hhincome_lessthan10000,hhincome_10to14999,hhincome_15to19999,hhincome_20to24999,hhincome_25to29999,hhincome_30to34999,hhincome_35to39999,hhincome_40to49999,hhincome_50to59999,hhincome_60to74999,hhincome_75to99999,hhincome_100to124999,hhincome125to149999,hhincome150to199999,hhincome200ormore,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,structures_total_yearbuilt_series,structures_built2014orlater,structures_built2010to2013,structures_built2000to2009,structures_built1990to1999,structures_built1980to1989,structures_built1970to1979,structures_built1960to1969,structures_built1950to1959,structures_built1940to1949,structures_built1939orearlier,structures_medianyearbuilt,commute_total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,vehicles_total_series2,vehicles_none,vehicles_one,vehicles_two,vehicles_three,vehicles_four,vehicles_fiveormore,foreignborn_total,fb_europe,fb_eur_northern,fb_eur_n_ireland,fb_eur_n_denmark,fb_eur_n_norway,fb_eur_n_sweden,fb_eur_n_uk,fb_eur_n_excluding england and scotland,fb_eur_n_england,fb_eur_n_scotland,fb_eur_n_other,fb_eur_western,fb_eur_w_austria,fb_eur_w_belgium,fb_eur_w_france,fb_eur_w_germany,fb_eur_w_netherlands,fb_eur_w_switzerland,fb_eur_w_other,fb_eur_southern,fb_eur_s_greece,fb_eur_s_italy,fb_eur_s_portugal,fb_eur_s_azoresislands,fb_eur_s_spain,fb_eur_s_other,fb_eur_eastern,fb_eur_e_albania,fb_eur_e_belarus,fb_eur_e_bosniaandherzegovina,fb_eur_e_bulgaria,fb_eur_e_croatia,fb_eur_e_czechoslovakia,fb_eur_e_hungary,fb_eur_e_latvia,fb_eur_e_lithuania,fb_eur_e_macedonia,fb_eur_e_moldova,fb_eur_e_poland,fb_eur_e_romania,fb_eur_e_russia,fb_eur_e_serbia,fb_eur_e_ukraine,fb_eur_e_other,fb_eur_nec,fb_asia,fb_as_eastern,fb_as_e_china,fb_as_e_chinanohongkongortaiwan,fb_as_e_hongkong,fb_as_e_taiwan,fb_as_e_japan,fb_as_e_korea,fb_as_e_other,fb_as_southcentral,fb_as_sc_afghanistan,fb_as_sc_bangladesh,fb_as_sc_india,fb_as_sc_iran,fb_as_sc_kazakhstan,fb_as_sc_nepal,fb_as_sc_pakistan,fb_as_sc_srilanka,fb_as_sc_uzbekistan,fb_as_sc_other,fb_as_southeastern,fb_as_se_burma,fb_as_se_cambodia,fb_as_se_indonesia,fb_as_se_laos,fb_as_se_malaysia,fb_as_se_philippines,fb_as_se_singapore,fb_as_se_thailand,fb_as_se_vietnam,fb_as_se_other,fb_as_western,fb_as_w_armenia,fb_as_w_iraq,fb_as_w_israel,fb_as_w_jordan,fb_as_w_kuwait,fb_as_w_lebanon,fb_as_w_saudiarabia,fb_as_w_syria,fb_as_w_turkey,fb_as_w_yemen,fb_as_w_other,fb_as_nec,fb_africa,fb_af_eastern,fb_af_e_eritrea,fb_af_e_ethiopia,fb_af_e_kenya,fb_af_e_somalia,fb_af_e_uganda,fb_af_e_zimbabwe,fb_af_e_other,fb_af_middle,fb_af_m_cameroon,fb_af_m_congo,fb_af_m_democraticrepublicofcongo,fb_af_m_other,fb_af_northern,fb_af_n_egypt,fb_af_n_morocco,fb_af_n_sudan,fb_af_n_other,fb_af_southern,fb_af_s_southafrica,fb_af_s_other,fb_af_western,fb_af_w_caboverde,fb_af_w_ghana,fb_af_w_liberia,fb_af_w_nigeria,fb_af_w_senegal,fb_af_w_sierraleone,fb_af_w_other,fb_af_nec,fb_oceania,fb_oc_australianewzealandsubregion,fb_oc_australianewzealandsubregion_australia,fb_oc_australianewzealandsubregion_other,fb_oc_fiji,fb_oc_micronesia,fb_oc_nec,fb_americas,fb_am_latinamerica,fb_am_la_caribbean,fb_am_la_cbb_bahamas,fb_am_la_cbb_barbados,fb_am_la_cbb_cuba,fb_am_la_cbb_dominica,fb_am_la_cbb_dominicanrepublic,fb_am_la_cbb_grenada,fb_am_la_cbb_haiti,fb_am_la_cbb_jamaica,fb_am_la_cbb_stvincentandthegrenadines,fb_am_la_cbb_trinidadandtobago,fb_am_la_cbb_westindies,fb_am_la_cbb_other,fb_am_la_centralamerica,fb_am_la_centr_belize,fb_am_la_centr_costarica,fb_am_la_centr_elsalvador,fb_am_la_centr_guatemala,fb_am_la_centr_honduras,fb_am_la_centr_mexico,fb_am_la_centr_nicaragua,fb_am_la_centr_panama,fb_am_la_centr_other,fb_am_la_southamerica,fb_am_la_s_argentina,fb_am_la_s_bolivia,fb_am_la_s_brazil,fb_am_la_s_chile,fb_am_la_s_columbia,fb_am_la_s_ecuador,fb_am_la_s_guyana,fb_am_la_s_peru,fb_am_la_s_uruguay,fb_am_la_s_venezuela,fb_am_la_s_other,fb_am_northern,fb_am_n_canada,fb_am_n_other,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_22to24_employed,lfstatus_mciv_22to24_unemployed,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,lfstatus_mciv_30to34_unemployed,lfstatus_mciv_35to44,lfstatus_mciv_35to44_employed,lfstatus_mciv_35to44_unemployed,lfstatus_mciv_45to54,lfstatus_mciv_45to54_employed,lfstatus_mciv_45to54_unemployed,lfstatus_mciv_55to59,lfstatus_mciv_55to59_employed,lfstatus_mciv_55to59_unemployed,lfstatus_mciv_60to61,lfstatus_mciv_60to61_employed,lfstatus_mciv_60to61_unemployed,lfstatus_mciv_62to64,lfstatus_mciv_62to64_employed,lfstatus_mciv_62to64_unemployed,lfstatus_mciv_65to69,lfstatus_mciv_65to69_employed,lfstatus_mciv_65to69_unemployed,lfstatus_mciv_70to74,lfstatus_mciv_70to74_employed,lfstatus_mciv_70to74_unemployed,lfstatus_mciv_75+,lfstatus_mciv_75+_employed,lfstatus_mciv_75+_unemployed,lfstatus_fciv_16to19,lfstatus_fciv_16to19_employed,lfstatus_fciv_16to19_unemployed,lfstatus_fciv_20to21,lfstatus_fciv_20to21_employed,lfstatus_fciv_20to21_unemployed,lfstatus_fciv_22to24,lfstatus_fciv_22to24_employed,lfstatus_fciv_22to24_unemployed,lfstatus_fciv_25to29,lfstatus_fciv_25to29_employed,lfstatus_fciv_25to29_unemployed,lfstatus_fciv_30to34,lfstatus_fciv_30to34_employed,lfstatus_fciv_30to34_unemployed,lfstatus_fciv_35to44,lfstatus_fciv_35to44_employed,lfstatus_fciv_35to44_unemployed,lfstatus_fciv_45to54,lfstatus_fciv_45to54_employed,lfstatus_fciv_45to54_unemployed,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+_employed,lfstatus_fciv_75+_unemployed,percapita_income,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information,industry_m_finance_insurance_realestate_rental,industry_m_finrent_finance_insurance,industry_m_finrent_realestate_rental,industry_m_professional_scientific_managementadmin_waste,industry_m_profwaste_professional_scientific_technicalservices,industry_m_profwaste_managementcompaniesenterprises,industry_m_adminandsupportandwaste,industry_m_educational_healthcare_socialassistance,industry_m_edsocial_educational,industry_m_edsocial_healthcare_socialassistance,industry_m_arts_entertainmentrec_accommodation_food,industry_m_artsaccom_arts_entertainmentrec,industry_m_artsaccom_accommodation_food,industry_m_otherservices_notpublicadmin,industry_m_publicadmin,industry_sexbyindustrycivilianpop_totalfemale,industry_f_agriculture_forestry_fishing_hunting_mining,industry_f_agmining_agriculture_forestry_fishing_hunting,industry_f_agmining_mining_quarrying_oilandgas,industry_f_construction,industry_f_manufacturing,industry_f_wholesaletrade,industry_f_retailtrade,industry_f_transportation_warehousing_utilities,industry_f_transut_transportation_warehousing,industry_f_transut_utilities,industry_f_information,industry_f_finance_insurance_realestate_rental,industry_f_finrent_finance_insurance,industry_f_finrent_realestate_rental,industry_f_professional_scientific_managementadmin_waste,industry_f_profwaste_professional_scientific_technicalservices,industry_f_profwaste_managementcompaniesenterprises,industry_f_adminandsupportandwaste,industry_f_educational_healthcare_socialassistance,industry_f_edsocial_educational,industry_f_edsocial_healthcare_socialassistance,industry_f_arts_entertainmentrec_accommodation_food,industry_f_artsaccom_arts_entertainmentrec,industry_f_artsaccom_accommodation_food,industry_f_otherservices_notpublicadmin,industry_f_publicadmin,occupation_sexbyoccupationcivilianpop_total_series,occupation_sexbyoccupationcivilianpop_totalmale,occupation_m_management,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_management,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_e

In [106]:
transp = data.transpose()
transp.columns = transp.iloc[0]
transp.head()

NAME,"Stewart County, Tennessee","Montgomery County, Tennessee","Houston County, Tennessee","Humphreys County, Tennessee","Dickson County, Tennessee","Cheatham County, Tennessee","Robertson County, Tennessee","Sumner County, Tennessee","Davidson County, Tennessee","Wilson County, Tennessee","Trousdale County, Tennessee","Williamson County, Tennessee","Rutherford County, Tennessee","Maury County, Tennessee","Ashland City town, Tennessee","Burns town, Tennessee","Charlotte town, Tennessee","Clarksville city, Tennessee","Dickson city, Tennessee","Eagleville city, Tennessee","Gallatin city, Tennessee","Hartsville/Trousdale County, Tennessee","Kingston Springs town, Tennessee","La Vergne city, Tennessee","Lebanon city, Tennessee","McEwen city, Tennessee","Mount Juliet city, Tennessee","Murfreesboro city, Tennessee","New Johnsonville city, Tennessee","Pegram town, Tennessee","Pleasant View city, Tennessee","Slayden town, Tennessee","Smyrna town, Tennessee","Vanleer town, Tennessee","Watertown city, Tennessee","Waverly city, Tennessee","White Bluff town, Tennessee",Tennessee
NAME,"Stewart County, Tennessee","Montgomery County, Tennessee","Houston County, Tennessee","Humphreys County, Tennessee","Dickson County, Tennessee","Cheatham County, Tennessee","Robertson County, Tennessee","Sumner County, Tennessee","Davidson County, Tennessee","Wilson County, Tennessee","Trousdale County, Tennessee","Williamson County, Tennessee","Rutherford County, Tennessee","Maury County, Tennessee","Ashland City town, Tennessee","Burns town, Tennessee","Charlotte town, Tennessee","Clarksville city, Tennessee","Dickson city, Tennessee","Eagleville city, Tennessee","Gallatin city, Tennessee","Hartsville/Trousdale County, Tennessee","Kingston Springs town, Tennessee","La Vergne city, Tennessee","Lebanon city, Tennessee","McEwen city, Tennessee","Mount Juliet city, Tennessee","Murfreesboro city, Tennessee","New Johnsonville city, Tennessee","Pegram town, Tennessee","Pleasant View city, Tennessee","Slayden town, Tennessee","Smyrna town, Tennessee","Vanleer town, Tennessee","Watertown city, Tennessee","Waverly city, Tennessee","White Bluff town, Tennessee",Tennessee
GEO_ID,0500000US47161,0500000US47125,0500000US47083,0500000US47085,0500000US47043,0500000US47021,0500000US47147,0500000US47165,0500000US47037,0500000US47189,0500000US47169,0500000US47187,0500000US47149,0500000US47119,1600000US4702180,1600000US4709880,1600000US4713080,1600000US4715160,1600000US4720620,1600000US4722360,1600000US4728540,1600000US4732742,1600000US4739660,1600000US4741200,1600000US4741520,1600000US4744840,1600000US4750780,1600000US4751560,1600000US4752820,1600000US4757480,1600000US4759560,1600000US4769080,1600000US4769420,1600000US4776860,1600000US4778320,1600000US4778560,1600000US4779980,0400000US47
agebysex_total_series,13553,204992,8201,18528,53289,40539,70982,187680,690540,140604,10910,232380,324139,94615,4720,1711,2115,156092,15500,943,40262,10910,2744,35556,34759,1802,35834,141704,1930,2492,4660,123,50820,418,1698,4124,3583,6772268
age_total_male,6572,102205,4119,9113,26246,20221,35176,91606,332527,68930,6668,113906,159299,45700,2298,839,1130,78420,7505,472,20160,6668,1377,17716,16515,844,17691,68891,1045,1276,2281,62,25143,241,732,1988,1770,3304462
age_m_u5,353,8916,216,538,1733,1192,2325,5776,23406,4318,373,6932,10772,3200,85,46,19,7584,714,48,1416,373,99,1655,1205,96,1252,4640,79,20,51,0,1848,11,63,33,159,208551

In [107]:
transp = transp.loc[transp['Stewart County, Tennessee'] != 'Stewart County, Tennessee']
transp = transp.loc[transp['Stewart County, Tennessee'] != '0500000US47161']

In [108]:
transp.head()

NAME,"Stewart County, Tennessee","Montgomery County, Tennessee","Houston County, Tennessee","Humphreys County, Tennessee","Dickson County, Tennessee","Cheatham County, Tennessee","Robertson County, Tennessee","Sumner County, Tennessee","Davidson County, Tennessee","Wilson County, Tennessee","Trousdale County, Tennessee","Williamson County, Tennessee","Rutherford County, Tennessee","Maury County, Tennessee","Ashland City town, Tennessee","Burns town, Tennessee","Charlotte town, Tennessee","Clarksville city, Tennessee","Dickson city, Tennessee","Eagleville city, Tennessee","Gallatin city, Tennessee","Hartsville/Trousdale County, Tennessee","Kingston Springs town, Tennessee","La Vergne city, Tennessee","Lebanon city, Tennessee","McEwen city, Tennessee","Mount Juliet city, Tennessee","Murfreesboro city, Tennessee","New Johnsonville city, Tennessee","Pegram town, Tennessee","Pleasant View city, Tennessee","Slayden town, Tennessee","Smyrna town, Tennessee","Vanleer town, Tennessee","Watertown city, Tennessee","Waverly city, Tennessee","White Bluff town, Tennessee",Tennessee
agebysex_total_series,13553,204992,8201,18528,53289,40539,70982,187680,690540,140604,10910,232380,324139,94615,4720,1711,2115,156092,15500,943,40262,10910,2744,35556,34759,1802,35834,141704,1930,2492,4660,123,50820,418,1698,4124,3583,6772268
age_total_male,6572,102205,4119,9113,26246,20221,35176,91606,332527,68930,6668,113906,159299,45700,2298,839,1130,78420,7505,472,20160,6668,1377,17716,16515,844,17691,68891,1045,1276,2281,62,25143,241,732,1988,1770,3304462
age_m_u5,353,8916,216,538,1733,1192,2325,5776,23406,4318,373,6932,10772,3200,85,46,19,7584,714,48,1416,373,99,1655,1205,96,1252,4640,79,20,51,0,1848,11,63,33,159,208551
age_m_5to9,476,7959,347,565,1662,1165,2352,6523,18746,4573,425,9230,11045,2504,130,59,103,6061,527,60,1537,425,91,1064,1235,23,1373,4664,41,59,182,7,2435,8,35,124,98,208045
age_m_10to14,364,7229,234,663,1850,1407,2491,6312,20115,5100,268,9690,12034,3692,198,37,61,5017,574,40,1607,268,93,1661,1129,48,1699,4978,87,86,204,7,1688,28,67,126,86,222622

In [109]:
numcols = list(transp.columns)
numcols
transp[numcols] = transp[numcols].astype(float)

In [110]:
data = transp

In [123]:
GNRCCounties = [data['Stewart County, Tennessee'],data['Montgomery County, Tennessee'],data['Houston County, Tennessee'],data['Humphreys County, Tennessee'],
                data['Dickson County, Tennessee'],data['Cheatham County, Tennessee'],data['Robertson County, Tennessee'],data['Sumner County, Tennessee'],
                data['Davidson County, Tennessee'],data['Wilson County, Tennessee'],data['Trousdale County, Tennessee'],data['Williamson County, Tennessee'],
                data['Rutherford County, Tennessee']]
data['GNRC'] = sum(GNRCCounties)

In [124]:
MPOCounties = [data['Robertson County, Tennessee'],data['Sumner County, Tennessee'],data['Davidson County, Tennessee'],data['Wilson County, Tennessee'],
               data['Williamson County, Tennessee'],data['Rutherford County, Tennessee'],data['Maury County, Tennessee']]
data['MPO'] = sum(MPOCounties)

In [132]:
RuthInc = [data['Eagleville city, Tennessee'],data['La Vergne city, Tennessee'],data['Murfreesboro city, Tennessee'],data['Smyrna town, Tennessee']]
data['Rutherford Incorporated'] = sum(RuthInc)
data['Rutherford Unincorporated'] = data['Rutherford County, Tennessee'] - data['Rutherford Incorporated']
WilsonInc = [data['Lebanon city, Tennessee'],data['Mount Juliet city, Tennessee'],data['Watertown city, Tennessee']]
data['Wilson Incorporated'] = sum(WilsonInc)
data['Wilson Unincorporated'] = data['Wilson County, Tennessee'] - data['Wilson Incorporated']
CheathInc = [data['Ashland City town, Tennessee'],data['Kingston Springs town, Tennessee'],data['Pegram town, Tennessee'],data['Pleasant View city, Tennessee']]
data['Cheatham Incorporated'] = sum(CheathInc)
data['Cheatham Unincorporated'] = data['Cheatham County, Tennessee'] - data['Cheatham Incorporated']
DicksInc = [data['Burns town, Tennessee'],data['Charlotte town, Tennessee'],data['Dickson city, Tennessee'],data['Slayden town, Tennessee'],
            data['Vanleer town, Tennessee'],data['White Bluff town, Tennessee']]
data['Dickson Incorporated'] = sum(DicksInc)
data['Dickson Unincorporated'] = data['Dickson County, Tennessee'] - data['Dickson Incorporated']
HumphInc = [data['McEwen city, Tennessee'],data['New Johnsonville city, Tennessee'],data['Waverly city, Tennessee']]
data['Humphreys Incorporated'] = sum(HumphInc)
data['Humphreys Unincorporated'] = data['Humphreys County, Tennessee'] - data['Humphreys Incorporated']
data['Montgomery Incorporated'] = data['Clarksville city, Tennessee']
data['Montgomery Unincorporated'] = data['Montgomery County, Tennessee'] - data['Montgomery Incorporated']
data['Trousdale Incorporated'] = data['Hartsville/Trousdale County, Tennessee']
data['Trousdale Unincorporated'] = data['Trousdale County, Tennessee'] - data['Trousdale Incorporated']

Not dropping any places right now.

In [133]:
data.head()

NAME,"Stewart County, Tennessee","Montgomery County, Tennessee","Houston County, Tennessee","Humphreys County, Tennessee","Dickson County, Tennessee","Cheatham County, Tennessee","Robertson County, Tennessee","Sumner County, Tennessee","Davidson County, Tennessee","Wilson County, Tennessee","Trousdale County, Tennessee","Williamson County, Tennessee","Rutherford County, Tennessee","Maury County, Tennessee","Ashland City town, Tennessee","Burns town, Tennessee","Charlotte town, Tennessee","Clarksville city, Tennessee","Dickson city, Tennessee","Eagleville city, Tennessee","Gallatin city, Tennessee","Hartsville/Trousdale County, Tennessee","Kingston Springs town, Tennessee","La Vergne city, Tennessee","Lebanon city, Tennessee","McEwen city, Tennessee","Mount Juliet city, Tennessee","Murfreesboro city, Tennessee","New Johnsonville city, Tennessee","Pegram town, Tennessee","Pleasant View city, Tennessee","Slayden town, Tennessee","Smyrna town, Tennessee","Vanleer town, Tennessee","Watertown city, Tennessee","Waverly city, Tennessee","White Bluff town, Tennessee",Tennessee,GNRC,MPO,Rutherford Incorporated,Rutherford Unincorporated,Wilson Incorporated,Wilson Unincorporated,Cheatham Incorporated,Cheatham Unincorporated,Dickson Incorporated,Dickson Unincorporated,Humphreys Incorporated,Humphreys Unincorporated,Montgomery Incorporated,Montgomery Unincorporated,Trousdale Incorporated,Trousdale Unincorporated
agebysex_total_series,13553.0,204992.0,8201.0,18528.0,53289.0,40539.0,70982.0,187680.0,690540.0,140604.0,10910.0,232380.0,324139.0,94615.0,4720.0,1711.0,2115.0,156092.0,15500.0,943.0,40262.0,10910.0,2744.0,35556.0,34759.0,1802.0,35834.0,141704.0,1930.0,2492.0,4660.0,123.0,50820.0,418.0,1698.0,4124.0,3583.0,6772268.0,1996337.0,1740940.0,229023.0,95116.0,72291.0,68313.0,14616.0,25923.0,23450.0,29839.0,7856.0,10672.0,156092.0,48900.0,10910.0,0.0
age_total_male,6572.0,102205.0,4119.0,9113.0,26246.0,20221.0,35176.0,91606.0,332527.0,68930.0,6668.0,113906.0,159299.0,45700.0,2298.0,839.0,1130.0,78420.0,7505.0,472.0,20160.0,6668.0,1377.0,17716.0,16515.0,844.0,17691.0,68891.0,1045.0,1276.0,2281.0,62.0,25143.0,241.0,732.0,1988.0,1770.0,3304462.0,976588.0,847144.0,112222.0,47077.0,34938.0,33992.0,7232.0,12989.0,11547.0,14699.0,3877.0,5236.0,78420.0,23785.0,6668.0,0.0
age_m_u5,353.0,8916.0,216.0,538.0,1733.0,1192.0,2325.0,5776.0,23406.0,4318.0,373.0,6932.0,10772.0,3200.0,85.0,46.0,19.0,7584.0,714.0,48.0,1416.0,373.0,99.0,1655.0,1205.0,96.0,1252.0,4640.0,79.0,20.0,51.0,0.0,1848.0,11.0,63.0,33.0,159.0,208551.0,66850.0,56729.0,8191.0,2581.0,2520.0,1798.0,255.0,937.0,949.0,784.0,208.0,330.0,7584.0,1332.0,373.0,0.0
age_m_5to9,476.0,7959.0,347.0,565.0,1662.0,1165.0,2352.0,6523.0,18746.0,4573.0,425.0,9230.0,11045.0,2504.0,130.0,59.0,103.0,6061.0,527.0,60.0,1537.0,425.0,91.0,1064.0,1235.0,23.0,1373.0,4664.0,41.0,59.0,182.0,7.0,2435.0,8.0,35.0,124.0,98.0,208045.0,65068.0,54973.0,8223.0,2822.0,2643.0,1930.0,462.0,703.0,802.0,860.0,188.0,377.0,6061.0,1898.0,425.0,0.0
age_m_10to14,364.0,7229.0,234.0,663.0,1850.0,1407.0,2491.0,6312.0,20115.0,5100.0,268.0,9690.0,12034.0,3692.0,198.0,37.0,61.0,5017.0,574.0,40.0,1607.0,268.0,93.0,1661.0,1129.0,48.0,1699.0,4978.0,87.0,86.0,204.0,7.0,1688.0,28.0,67.0,126.0,86.0,222622.0,67757.0,59434.0,8367.0,3667.0,2895.0,2205.0,581.0,826.0,793.0,1057.0,261.0,402.0,5017.0,2212.0,268.0,0.0

In [134]:
ok = data.transpose().reset_index()

In [135]:
ok.head()

,NAME,agebysex_total_series,age_total_male,age_m_u5,age_m_5to9,age_m_10to14,age_m_15to17,age_m_18to19,age_m_20,age_m_21,age_m_22to24,age_m_25to29,age_m_30to34,age_m_35to39,age_m_40to44,age_m_45to49,age_m_50to54,age_m_55to59,age_m_60to61,age_m_62to64,age_m_65to66,age_m_67to69,age_m_70to74,age_m_75to79,age_m_80to84,age_m_85+,age_total_female,age_f_u5,age_f_5to9,age_f_10to14,age_f_15to17,age_f_18to19,age_f_20,age_f_21,age_f_22to24,age_f_25to29,age_f_30to34,age_f_35to39,age_f_40to44,age_f_45to49,age_f_50to54,age_f_55to59,age_f_60to61,age_f_62to64,age_f_65to66,age_f_67to69,age_f_70to74,age_f_75to79,age_f_80to84,age_f_85+,raceeth_white_alone,raceeth_blackafricanamerican_alone,raceeth_americanindianalaskanative_alone,raceeth_asian_alone,raceeth_nativehawaiianotherpacificislander_alone,raceeth_someotherrace_alone,raceeth_twoormoreraces_alone,raceeth_whitealone_nothispanicorlatino,raceeth_hispanicorlatino,hhsize_avg,healthcoverage_total_healthcare_series,healthcoverage_total_mallhealthcare,healthcoverage_mu6_all,healthcoverage_mu6_w,healthcoverage_mu6_wo,healthcoverage_m6to18_all,healthcoverage_m6to18_w,healthcoverage_m6to18_wo,healthcoverage_m19to25_all,healthcoverage_m19to25_w,healthcoverage_m19to25_wo,healthcoverage_m26to34_all,healthcoverage_m26to34_w,healthcoverage_m26to34_wo,healthcoverage_m35to44_all,healthcoverage_m35to44_w,healthcoverage_m35to44_wo,healthcoverage_m45to54_all,healthcoverage_m45to54_w,healthcoverage_m45to54_wo,healthcoverage_m55to64_all,healthcoverage_m55to64_w,healthcoverage_m55to64_wo,healthcoverage_m65to74_all,healthcoverage_m65to74_w,healthcoverage_m65to74_wo,healthcoverage_m75+_all,healthcoverage_m75+_w,healthcoverage_m75+_wo,healthcoverage_total_fallhealthcare,healthcoverage_fu6_all,healthcoverage_fu6_w,healthcoverage_fu6_wo,healthcoverage_f6to18_all,healthcoverage_f6to18_w,healthcoverage_f6to18_wo,healthcoverage_f19to25_all,healthcoverage_f19to25_w,healthcoverage_f19to25_wo,healthcoverage_f26to34_all,healthcoverage_f26to34_w,healthcoverage_f26to34_wo,healthcoverage_f35to44_all,healthcoverage_f35to44_w,healthcoverage_f35to44_wo,healthcoverage_f45to54_all,healthcoverage_f45to54_w,healthcoverage_f45to54_wo,healthcoverage_f55to64_all,healthcoverage_f55to64_w,healthcoverage_f55to64_wo,healthcoverage_f65to74_all,healthcoverage_f65to74_w,healthcoverage_f65to74_wo,healthcoverage_f75+_all,healthcoverage_f75+_w,healthcoverage_f75+_wo,healthcoverage_total_privatehealthcare_series,healthcoverage_total_mprivate,healthcoverage_mu6_privateall,healthcoverage_mu6_wprivate,healthcoverage_mu6_woprivate,healthcoverage_m6to18_privateall,healthcoverage_m6to18_wprivate,healthcoverage_m6to18_woprivate,healthcoverage_m19to25_privateall,healthcoverage_m19to25_wprivate,healthcoverage_m19to25_woprivate,healthcoverage_m26to34_privateall,healthcoverage_m26to34_wprivate,healthcoverage_m26to34_woprivate,healthcoverage_m35to44_privateall,healthcoverage_m35to44_wprivate,healthcoverage_m35to44_woprivate,healthcoverage_m45to54_privateall,healthcoverage_m45to54_wprivate,healthcoverage_m45to54_woprivate,healthcoverage_m55to64_privateall,healthcoverage_m55to64_wprivate,healthcoverage_m55to64_woprivate,healthcoverage_m65to74_privateall,healthcoverage_m65to74_wprivate,healthcoverage_m65to74_woprivate,healthcoverage_m75+_privateall,healthcoverage_m75+_wprivate,healthcoverage_m75+_woprivate,healthcoverage_total_fprivate,healthcoverage_fu6_privateall,healthcoverage_fu6_wprivate,healthcoverage_fu6_woprivate,healthcoverage_f6to18_privateall,healthcoverage_f6to18_wprivate,healthcoverage_f6to18_woprivate,healthcoverage_f19to25_privateall,healthcoverage_f19to25_wprivate,healthcoverage_f19to25_woprivate,healthcoverage_f26to34_privateall,healthcoverage_f26to34_wprivate,healthcoverage_f26to34_woprivate,healthcoverage_f35to44_privateall,healthcoverage_f35to44_wprivate,healthcoverage_f35to44_woprivate,healthcoverage_f45to54_privateall,healthcoverage_f45to54_wprivate,healthcoverage_f45to54_woprivate,healthcoverage_f55to64_privateall,healthcoverage_f55to64_wprivate,healthcoverage_f55to64_woprivate,healthcoverage_f65to74_privateall,healthcoverage_f65to74_wprivate,healthcoverage_f65to74_woprivate,healthcoverage_f75+_privateall,healthcoverage_f75+_wprivate,healthcoverage_f75+_woprivate,healthcoverage_total_publichealthcare_series,healthcoverage_total_mpublic,healthcoverage_mu6_publicall,healthcoverage_mu6_wpublic,healthcoverage_mu6_wopublic,healthcoverage_m6to18_publicall,healthcoverage_m6to18_wpublic,healthcoverage_m6to18_wopublic,healthcoverage_m19to25_publicall,healthcoverage_m19to25_wpublic,healthcoverage_m19to25_wopublic,healthcoverage_m26to34_publicall,healthcoverage_m26to34_wpublic,healthcoverage_m26to34_wopublic,healthcoverage_m35to44_publicall,healthcoverage_m35to44_wpublic,healthcoverage_m35to44_wopublic,healthcoverage_m45to54_publicall,healthcoverage_m45to54_wpublic,healthcoverage_m45to54_wopublic,healthcoverage_m55to64_publicall,healthcoverage_m55to64_wpublic,healthcoverage_m55to64_wopublic,healthcoverage_m65to74_publicall,healthcoverage_m65to74_wpublic,healthcoverage_m65to74_wopublic,healthcoverage_m75+_publicall,healthcoverage_m75+_wpublic,healthcoverage_m75+_wopublic,healthcoverage_total_fpublic,healthcoverage_fu6_publicall,healthcoverage_fu6_wpublic,healthcoverage_fu6_wopublic,healthcoverage_f6to18_publicall,healthcoverage_f6to18_wpublic,healthcoverage_f6to18_wopublic,healthcoverage_f19to25_publicall,healthcoverage_f19to25_wpublic,healthcoverage_f19to25_wopublic,healthcoverage_f26to34_publicall,healthcoverage_f26to34_wpublic,healthcoverage_f26to34_wopublic,healthcoverage_f35to44_publicall,healthcoverage_f35to44_wpublic,healthcoverage_f35to44_wopublic,healthcoverage_f45to54_publicall,healthcoverage_f45to54_wpublic,healthcoverage_f45to54_wopublic,healthcoverage_f55to64_publicall,healthcoverage_f55to64_wpublic,healthcoverage_f55to64_wopublic,healthcoverage_f65to74_publicall,healthcoverage_f65to74_wpublic,healthcoverage_f65to74_wopublic,healthcoverage_f75+_publicall,healthcoverage_f75+_wpublic,healthcoverage_f75+_wopublic,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,hhincome_total_series,hhincome_lessthan10000,hhincome_10to14999,hhincome_15to19999,hhincome_20to24999,hhincome_25to29999,hhincome_30to34999,hhincome_35to39999,hhincome_40to49999,hhincome_50to59999,hhincome_60to74999,hhincome_75to99999,hhincome_100to124999,hhincome125to149999,hhincome150to199999,hhincome200ormore,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,structures_total_yearbuilt_series,structures_built2014orlater,structures_built2010to2013,structures_built2000to2009,structures_built1990to1999,structures_built1980to1989,structures_built1970to1979,structures_built1960to1969,structures_built1950to1959,structures_built1940to1949,structures_built1939orearlier,structures_medianyearbuilt,commute_total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,vehicles_total_series2,vehicles_none,vehicles_one,vehicles_two,vehicles_three,vehicles_four,vehicles_fiveormore,foreignborn_total,fb_europe,fb_eur_northern,fb_eur_n_ireland,fb_eur_n_denmark,fb_eur_n_norway,fb_eur_n_sweden,fb_eur_n_uk,fb_eur_n_excluding england and scotland,fb_eur_n_england,fb_eur_n_scotland,fb_eur_n_other,fb_eur_western,fb_eur_w_austria,fb_eur_w_belgium,fb_eur_w_france,fb_eur_w_germany,fb_eur_w_netherlands,fb_eur_w_switzerland,fb_eur_w_other,fb_eur_southern,fb_eur_s_greece,fb_eur_s_italy,fb_eur_s_portugal,fb_eur_s_azoresislands,fb_eur_s_spain,fb_eur_s_other,fb_eur_eastern,fb_eur_e_albania,fb_eur_e_belarus,fb_eur_e_bosniaandherzegovina,fb_eur_e_bulgaria,fb_eur_e_croatia,fb_eur_e_czechoslovakia,fb_eur_e_hungary,fb_eur_e_latvia,fb_eur_e_lithuania,fb_eur_e_macedonia,fb_eur_e_moldova,fb_eur_e_poland,fb_eur_e_romania,fb_eur_e_russia,fb_eur_e_serbia,fb_eur_e_ukraine,fb_eur_e_other,fb_eur_nec,fb_asia,fb_as_eastern,fb_as_e_china,fb_as_e_chinanohongkongortaiwan,fb_as_e_hongkong,fb_as_e_taiwan,fb_as_e_japan,fb_as_e_korea,fb_as_e_other,fb_as_southcentral,fb_as_sc_afghanistan,fb_as_sc_bangladesh,fb_as_sc_india,fb_as_sc_iran,fb_as_sc_kazakhstan,fb_as_sc_nepal,fb_as_sc_pakistan,fb_as_sc_srilanka,fb_as_sc_uzbekistan,fb_as_sc_other,fb_as_southeastern,fb_as_se_burma,fb_as_se_cambodia,fb_as_se_indonesia,fb_as_se_laos,fb_as_se_malaysia,fb_as_se_philippines,fb_as_se_singapore,fb_as_se_thailand,fb_as_se_vietnam,fb_as_se_other,fb_as_western,fb_as_w_armenia,fb_as_w_iraq,fb_as_w_israel,fb_as_w_jordan,fb_as_w_kuwait,fb_as_w_lebanon,fb_as_w_saudiarabia,fb_as_w_syria,fb_as_w_turkey,fb_as_w_yemen,fb_as_w_other,fb_as_nec,fb_africa,fb_af_eastern,fb_af_e_eritrea,fb_af_e_ethiopia,fb_af_e_kenya,fb_af_e_somalia,fb_af_e_uganda,fb_af_e_zimbabwe,fb_af_e_other,fb_af_middle,fb_af_m_cameroon,fb_af_m_congo,fb_af_m_democraticrepublicofcongo,fb_af_m_other,fb_af_northern,fb_af_n_egypt,fb_af_n_morocco,fb_af_n_sudan,fb_af_n_other,fb_af_southern,fb_af_s_southafrica,fb_af_s_other,fb_af_western,fb_af_w_caboverde,fb_af_w_ghana,fb_af_w_liberia,fb_af_w_nigeria,fb_af_w_senegal,fb_af_w_sierraleone,fb_af_w_other,fb_af_nec,fb_oceania,fb_oc_australianewzealandsubregion,fb_oc_australianewzealandsubregion_australia,fb_oc_australianewzealandsubregion_other,fb_oc_fiji,fb_oc_micronesia,fb_oc_nec,fb_americas,fb_am_latinamerica,fb_am_la_caribbean,fb_am_la_cbb_bahamas,fb_am_la_cbb_barbados,fb_am_la_cbb_cuba,fb_am_la_cbb_dominica,fb_am_la_cbb_dominicanrepublic,fb_am_la_cbb_grenada,fb_am_la_cbb_haiti,fb_am_la_cbb_jamaica,fb_am_la_cbb_stvincentandthegrenadines,fb_am_la_cbb_trinidadandtobago,fb_am_la_cbb_westindies,fb_am_la_cbb_other,fb_am_la_centralamerica,fb_am_la_centr_belize,fb_am_la_centr_costarica,fb_am_la_centr_elsalvador,fb_am_la_centr_guatemala,fb_am_la_centr_honduras,fb_am_la_centr_mexico,fb_am_la_centr_nicaragua,fb_am_la_centr_panama,fb_am_la_centr_other,fb_am_la_southamerica,fb_am_la_s_argentina,fb_am_la_s_bolivia,fb_am_la_s_brazil,fb_am_la_s_chile,fb_am_la_s_columbia,fb_am_la_s_ecuador,fb_am_la_s_guyana,fb_am_la_s_peru,fb_am_la_s_uruguay,fb_am_la_s_venezuela,fb_am_la_s_other,fb_am_northern,fb_am_n_canada,fb_am_n_other,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_22to24_employed,lfstatus_mciv_22to24_unemployed,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,lfstatus_mciv_30to34_unemployed,lfstatus_mciv_35to44,lfstatus_mciv_35to44_employed,lfstatus_mciv_35to44_unemployed,lfstatus_mciv_45to54,lfstatus_mciv_45to54_employed,lfstatus_mciv_45to54_unemployed,lfstatus_mciv_55to59,lfstatus_mciv_55to59_employed,lfstatus_mciv_55to59_unemployed,lfstatus_mciv_60to61,lfstatus_mciv_60to61_employed,lfstatus_mciv_60to61_unemployed,lfstatus_mciv_62to64,lfstatus_mciv_62to64_employed,lfstatus_mciv_62to64_unemployed,lfstatus_mciv_65to69,lfstatus_mciv_65to69_employed,lfstatus_mciv_65to69_unemployed,lfstatus_mciv_70to74,lfstatus_mciv_70to74_employed,lfstatus_mciv_70to74_unemployed,lfstatus_mciv_75+,lfstatus_mciv_75+_employed,lfstatus_mciv_75+_unemployed,lfstatus_fciv_16to19,lfstatus_fciv_16to19_employed,lfstatus_fciv_16to19_unemployed,lfstatus_fciv_20to21,lfstatus_fciv_20to21_employed,lfstatus_fciv_20to21_unemployed,lfstatus_fciv_22to24,lfstatus_fciv_22to24_employed,lfstatus_fciv_22to24_unemployed,lfstatus_fciv_25to29,lfstatus_fciv_25to29_employed,lfstatus_fciv_25to29_unemployed,lfstatus_fciv_30to34,lfstatus_fciv_30to34_employed,lfstatus_fciv_30to34_unemployed,lfstatus_fciv_35to44,lfstatus_fciv_35to44_employed,lfstatus_fciv_35to44_unemployed,lfstatus_fciv_45to54,lfstatus_fciv_45to54_employed,lfstatus_fciv_45to54_unemployed,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+_employed,lfstatus_fciv_75+_unemployed,percapita_income,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information,industry_m_finance_insurance_realestate_rental,industry_m_finrent_finance_insurance,industry_m_finrent_realestate_rental,industry_m_professional_scientific_managementadmin_waste,industry_m_profwaste_professional_scientific_technicalservices,industry_m_profwaste_managementcompaniesenterprises,industry_m_adminandsupportandwaste,industry_m_educational_healthcare_socialassistance,industry_m_edsocial_educational,industry_m_edsocial_healthcare_socialassistance,industry_m_arts_entertainmentrec_accommodation_food,industry_m_artsaccom_arts_entertainmentrec,industry_m_artsaccom_accommodation_food,industry_m_otherservices_notpublicadmin,industry_m_publicadmin,industry_sexbyindustrycivilianpop_totalfemale,industry_f_agriculture_forestry_fishing_hunting_mining,industry_f_agmining_agriculture_forestry_fishing_hunting,industry_f_agmining_mining_quarrying_oilandgas,industry_f_construction,industry_f_manufacturing,industry_f_wholesaletrade,industry_f_retailtrade,industry_f_transportation_warehousing_utilities,industry_f_transut_transportation_warehousing,industry_f_transut_utilities,industry_f_information,industry_f_finance_insurance_realestate_rental,industry_f_finrent_finance_insurance,industry_f_finrent_realestate_rental,industry_f_professional_scientific_managementadmin_waste,industry_f_profwaste_professional_scientific_technicalservices,industry_f_profwaste_managementcompaniesenterprises,industry_f_adminandsupportandwaste,industry_f_educational_healthcare_socialassistance,industry_f_edsocial_educational,industry_f_edsocial_healthcare_socialassistance,industry_f_arts_entertainmentrec_accommodation_food,industry_f_artsaccom_arts_entertainmentrec,industry_f_artsaccom_accommodation_food,industry_f_otherservices_notpublicadmin,industry_f_publicadmin,occupation_sexbyoccupationcivilianpop_total_series,occupation_sexbyoccupationcivilianpop_totalmale,occupation_m_management,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_management,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educatio

In [136]:
ok.tail()

,NAME,agebysex_total_series,age_total_male,age_m_u5,age_m_5to9,age_m_10to14,age_m_15to17,age_m_18to19,age_m_20,age_m_21,age_m_22to24,age_m_25to29,age_m_30to34,age_m_35to39,age_m_40to44,age_m_45to49,age_m_50to54,age_m_55to59,age_m_60to61,age_m_62to64,age_m_65to66,age_m_67to69,age_m_70to74,age_m_75to79,age_m_80to84,age_m_85+,age_total_female,age_f_u5,age_f_5to9,age_f_10to14,age_f_15to17,age_f_18to19,age_f_20,age_f_21,age_f_22to24,age_f_25to29,age_f_30to34,age_f_35to39,age_f_40to44,age_f_45to49,age_f_50to54,age_f_55to59,age_f_60to61,age_f_62to64,age_f_65to66,age_f_67to69,age_f_70to74,age_f_75to79,age_f_80to84,age_f_85+,raceeth_white_alone,raceeth_blackafricanamerican_alone,raceeth_americanindianalaskanative_alone,raceeth_asian_alone,raceeth_nativehawaiianotherpacificislander_alone,raceeth_someotherrace_alone,raceeth_twoormoreraces_alone,raceeth_whitealone_nothispanicorlatino,raceeth_hispanicorlatino,hhsize_avg,healthcoverage_total_healthcare_series,healthcoverage_total_mallhealthcare,healthcoverage_mu6_all,healthcoverage_mu6_w,healthcoverage_mu6_wo,healthcoverage_m6to18_all,healthcoverage_m6to18_w,healthcoverage_m6to18_wo,healthcoverage_m19to25_all,healthcoverage_m19to25_w,healthcoverage_m19to25_wo,healthcoverage_m26to34_all,healthcoverage_m26to34_w,healthcoverage_m26to34_wo,healthcoverage_m35to44_all,healthcoverage_m35to44_w,healthcoverage_m35to44_wo,healthcoverage_m45to54_all,healthcoverage_m45to54_w,healthcoverage_m45to54_wo,healthcoverage_m55to64_all,healthcoverage_m55to64_w,healthcoverage_m55to64_wo,healthcoverage_m65to74_all,healthcoverage_m65to74_w,healthcoverage_m65to74_wo,healthcoverage_m75+_all,healthcoverage_m75+_w,healthcoverage_m75+_wo,healthcoverage_total_fallhealthcare,healthcoverage_fu6_all,healthcoverage_fu6_w,healthcoverage_fu6_wo,healthcoverage_f6to18_all,healthcoverage_f6to18_w,healthcoverage_f6to18_wo,healthcoverage_f19to25_all,healthcoverage_f19to25_w,healthcoverage_f19to25_wo,healthcoverage_f26to34_all,healthcoverage_f26to34_w,healthcoverage_f26to34_wo,healthcoverage_f35to44_all,healthcoverage_f35to44_w,healthcoverage_f35to44_wo,healthcoverage_f45to54_all,healthcoverage_f45to54_w,healthcoverage_f45to54_wo,healthcoverage_f55to64_all,healthcoverage_f55to64_w,healthcoverage_f55to64_wo,healthcoverage_f65to74_all,healthcoverage_f65to74_w,healthcoverage_f65to74_wo,healthcoverage_f75+_all,healthcoverage_f75+_w,healthcoverage_f75+_wo,healthcoverage_total_privatehealthcare_series,healthcoverage_total_mprivate,healthcoverage_mu6_privateall,healthcoverage_mu6_wprivate,healthcoverage_mu6_woprivate,healthcoverage_m6to18_privateall,healthcoverage_m6to18_wprivate,healthcoverage_m6to18_woprivate,healthcoverage_m19to25_privateall,healthcoverage_m19to25_wprivate,healthcoverage_m19to25_woprivate,healthcoverage_m26to34_privateall,healthcoverage_m26to34_wprivate,healthcoverage_m26to34_woprivate,healthcoverage_m35to44_privateall,healthcoverage_m35to44_wprivate,healthcoverage_m35to44_woprivate,healthcoverage_m45to54_privateall,healthcoverage_m45to54_wprivate,healthcoverage_m45to54_woprivate,healthcoverage_m55to64_privateall,healthcoverage_m55to64_wprivate,healthcoverage_m55to64_woprivate,healthcoverage_m65to74_privateall,healthcoverage_m65to74_wprivate,healthcoverage_m65to74_woprivate,healthcoverage_m75+_privateall,healthcoverage_m75+_wprivate,healthcoverage_m75+_woprivate,healthcoverage_total_fprivate,healthcoverage_fu6_privateall,healthcoverage_fu6_wprivate,healthcoverage_fu6_woprivate,healthcoverage_f6to18_privateall,healthcoverage_f6to18_wprivate,healthcoverage_f6to18_woprivate,healthcoverage_f19to25_privateall,healthcoverage_f19to25_wprivate,healthcoverage_f19to25_woprivate,healthcoverage_f26to34_privateall,healthcoverage_f26to34_wprivate,healthcoverage_f26to34_woprivate,healthcoverage_f35to44_privateall,healthcoverage_f35to44_wprivate,healthcoverage_f35to44_woprivate,healthcoverage_f45to54_privateall,healthcoverage_f45to54_wprivate,healthcoverage_f45to54_woprivate,healthcoverage_f55to64_privateall,healthcoverage_f55to64_wprivate,healthcoverage_f55to64_woprivate,healthcoverage_f65to74_privateall,healthcoverage_f65to74_wprivate,healthcoverage_f65to74_woprivate,healthcoverage_f75+_privateall,healthcoverage_f75+_wprivate,healthcoverage_f75+_woprivate,healthcoverage_total_publichealthcare_series,healthcoverage_total_mpublic,healthcoverage_mu6_publicall,healthcoverage_mu6_wpublic,healthcoverage_mu6_wopublic,healthcoverage_m6to18_publicall,healthcoverage_m6to18_wpublic,healthcoverage_m6to18_wopublic,healthcoverage_m19to25_publicall,healthcoverage_m19to25_wpublic,healthcoverage_m19to25_wopublic,healthcoverage_m26to34_publicall,healthcoverage_m26to34_wpublic,healthcoverage_m26to34_wopublic,healthcoverage_m35to44_publicall,healthcoverage_m35to44_wpublic,healthcoverage_m35to44_wopublic,healthcoverage_m45to54_publicall,healthcoverage_m45to54_wpublic,healthcoverage_m45to54_wopublic,healthcoverage_m55to64_publicall,healthcoverage_m55to64_wpublic,healthcoverage_m55to64_wopublic,healthcoverage_m65to74_publicall,healthcoverage_m65to74_wpublic,healthcoverage_m65to74_wopublic,healthcoverage_m75+_publicall,healthcoverage_m75+_wpublic,healthcoverage_m75+_wopublic,healthcoverage_total_fpublic,healthcoverage_fu6_publicall,healthcoverage_fu6_wpublic,healthcoverage_fu6_wopublic,healthcoverage_f6to18_publicall,healthcoverage_f6to18_wpublic,healthcoverage_f6to18_wopublic,healthcoverage_f19to25_publicall,healthcoverage_f19to25_wpublic,healthcoverage_f19to25_wopublic,healthcoverage_f26to34_publicall,healthcoverage_f26to34_wpublic,healthcoverage_f26to34_wopublic,healthcoverage_f35to44_publicall,healthcoverage_f35to44_wpublic,healthcoverage_f35to44_wopublic,healthcoverage_f45to54_publicall,healthcoverage_f45to54_wpublic,healthcoverage_f45to54_wopublic,healthcoverage_f55to64_publicall,healthcoverage_f55to64_wpublic,healthcoverage_f55to64_wopublic,healthcoverage_f65to74_publicall,healthcoverage_f65to74_wpublic,healthcoverage_f65to74_wopublic,healthcoverage_f75+_publicall,healthcoverage_f75+_wpublic,healthcoverage_f75+_wopublic,poverty_total_bysexbyage_series,poverty_belowlevel,units_allhousing,occupancy_total_series,occupancy_occupiedunits,occupancy_vacantunits,tenure_total_series,tenure_owneroccunits,tenure_renteroccunits,units_total_series,units_one_detached,units_one_attached,units_two,units_threetofour,units_fivetonine,units_tentonineteen,units_twentytofortynine,units_fiftyormore,units_mobilehome,units_boatrvvanetc,hhtype_total_series,hhtype_familyhh,hhtype_familyhh_marriedcouplefam,hhtype_familyhh_otherfam,hhtype_familyhh_malenospouse,hhtype_familyhh_femalenospouse,hhtype_nonfamhh,hhtype_nonfamhh_householderalone,hhtype_nonfamhh_householdernotalone,hhincome_median,hhincome_total_series,hhincome_lessthan10000,hhincome_10to14999,hhincome_15to19999,hhincome_20to24999,hhincome_25to29999,hhincome_30to34999,hhincome_35to39999,hhincome_40to49999,hhincome_50to59999,hhincome_60to74999,hhincome_75to99999,hhincome_100to124999,hhincome125to149999,hhincome150to199999,hhincome200ormore,housingcost_total_selectedownercosts%hhincome_series,housingcost_total%ownercostwmortgage_series,housingcost_%ownercost30to34.9_wmortgage,housingcost_%ownercost35to39.9_wmortgage,housingcost_%ownercost40to49.9_wmortgage,housingcost_%ownercost50+_wmortgage,housingcost_total%ownercostwomortgage_series,housingcost_%ownercost30to34.9_womortgage,housingcost_%ownercost35to39.9_womortgage,housingcost_%ownercost40to49.9_womortgage,housingcost_%ownercost50+_womortgage,housingcost_total_rent%hhincome_series,housingcost_%rentercost30to34.9,housingcost_%rentercost35to39.9,housingcost_%rentercost40to49.9,housingcost_%rentercost50+,housingcost_medvalue_ownerocc_wmortgage,housingcost_medvalue_ownerocc_womortgage,housingcost_mediangrossrent_renteroccupied,structures_total_yearbuilt_series,structures_built2014orlater,structures_built2010to2013,structures_built2000to2009,structures_built1990to1999,structures_built1980to1989,structures_built1970to1979,structures_built1960to1969,structures_built1950to1959,structures_built1940to1949,structures_built1939orearlier,structures_medianyearbuilt,commute_total_meansoftransportationtowork_series,commute_cartruckvan,commute_cartruckvan_drovealone,commute_cartruckvan_carpooled,commute_cartruckvan_carpooled_2ppl,commute_cartruckvan_carpooled_3ppl,commute_cartruckvan_carpooled_4ormoreppl,commute_publictransportation,commute_publictransportation_bus,commute_publictransportation_subwayorelevatedrail,commute_publictransportation_longdistancetrainorcommuterrail,commute_publictransportation_lightrailstreetcarortrolley,commute_publictransportation_ferryboat,commute_bicycle,commute_walk,commute_taxicabmotorcycleother,commute_workedfromhome,vehicles_total_series2,vehicles_none,vehicles_one,vehicles_two,vehicles_three,vehicles_four,vehicles_fiveormore,foreignborn_total,fb_europe,fb_eur_northern,fb_eur_n_ireland,fb_eur_n_denmark,fb_eur_n_norway,fb_eur_n_sweden,fb_eur_n_uk,fb_eur_n_excluding england and scotland,fb_eur_n_england,fb_eur_n_scotland,fb_eur_n_other,fb_eur_western,fb_eur_w_austria,fb_eur_w_belgium,fb_eur_w_france,fb_eur_w_germany,fb_eur_w_netherlands,fb_eur_w_switzerland,fb_eur_w_other,fb_eur_southern,fb_eur_s_greece,fb_eur_s_italy,fb_eur_s_portugal,fb_eur_s_azoresislands,fb_eur_s_spain,fb_eur_s_other,fb_eur_eastern,fb_eur_e_albania,fb_eur_e_belarus,fb_eur_e_bosniaandherzegovina,fb_eur_e_bulgaria,fb_eur_e_croatia,fb_eur_e_czechoslovakia,fb_eur_e_hungary,fb_eur_e_latvia,fb_eur_e_lithuania,fb_eur_e_macedonia,fb_eur_e_moldova,fb_eur_e_poland,fb_eur_e_romania,fb_eur_e_russia,fb_eur_e_serbia,fb_eur_e_ukraine,fb_eur_e_other,fb_eur_nec,fb_asia,fb_as_eastern,fb_as_e_china,fb_as_e_chinanohongkongortaiwan,fb_as_e_hongkong,fb_as_e_taiwan,fb_as_e_japan,fb_as_e_korea,fb_as_e_other,fb_as_southcentral,fb_as_sc_afghanistan,fb_as_sc_bangladesh,fb_as_sc_india,fb_as_sc_iran,fb_as_sc_kazakhstan,fb_as_sc_nepal,fb_as_sc_pakistan,fb_as_sc_srilanka,fb_as_sc_uzbekistan,fb_as_sc_other,fb_as_southeastern,fb_as_se_burma,fb_as_se_cambodia,fb_as_se_indonesia,fb_as_se_laos,fb_as_se_malaysia,fb_as_se_philippines,fb_as_se_singapore,fb_as_se_thailand,fb_as_se_vietnam,fb_as_se_other,fb_as_western,fb_as_w_armenia,fb_as_w_iraq,fb_as_w_israel,fb_as_w_jordan,fb_as_w_kuwait,fb_as_w_lebanon,fb_as_w_saudiarabia,fb_as_w_syria,fb_as_w_turkey,fb_as_w_yemen,fb_as_w_other,fb_as_nec,fb_africa,fb_af_eastern,fb_af_e_eritrea,fb_af_e_ethiopia,fb_af_e_kenya,fb_af_e_somalia,fb_af_e_uganda,fb_af_e_zimbabwe,fb_af_e_other,fb_af_middle,fb_af_m_cameroon,fb_af_m_congo,fb_af_m_democraticrepublicofcongo,fb_af_m_other,fb_af_northern,fb_af_n_egypt,fb_af_n_morocco,fb_af_n_sudan,fb_af_n_other,fb_af_southern,fb_af_s_southafrica,fb_af_s_other,fb_af_western,fb_af_w_caboverde,fb_af_w_ghana,fb_af_w_liberia,fb_af_w_nigeria,fb_af_w_senegal,fb_af_w_sierraleone,fb_af_w_other,fb_af_nec,fb_oceania,fb_oc_australianewzealandsubregion,fb_oc_australianewzealandsubregion_australia,fb_oc_australianewzealandsubregion_other,fb_oc_fiji,fb_oc_micronesia,fb_oc_nec,fb_americas,fb_am_latinamerica,fb_am_la_caribbean,fb_am_la_cbb_bahamas,fb_am_la_cbb_barbados,fb_am_la_cbb_cuba,fb_am_la_cbb_dominica,fb_am_la_cbb_dominicanrepublic,fb_am_la_cbb_grenada,fb_am_la_cbb_haiti,fb_am_la_cbb_jamaica,fb_am_la_cbb_stvincentandthegrenadines,fb_am_la_cbb_trinidadandtobago,fb_am_la_cbb_westindies,fb_am_la_cbb_other,fb_am_la_centralamerica,fb_am_la_centr_belize,fb_am_la_centr_costarica,fb_am_la_centr_elsalvador,fb_am_la_centr_guatemala,fb_am_la_centr_honduras,fb_am_la_centr_mexico,fb_am_la_centr_nicaragua,fb_am_la_centr_panama,fb_am_la_centr_other,fb_am_la_southamerica,fb_am_la_s_argentina,fb_am_la_s_bolivia,fb_am_la_s_brazil,fb_am_la_s_chile,fb_am_la_s_columbia,fb_am_la_s_ecuador,fb_am_la_s_guyana,fb_am_la_s_peru,fb_am_la_s_uruguay,fb_am_la_s_venezuela,fb_am_la_s_other,fb_am_northern,fb_am_n_canada,fb_am_n_other,attainment_total_over25_series,attainment_noschooling,attainment_nurseryschool,attainment_kindergarten,attainment_1stgrade,attainment_2ndgrade,attainment_3rdgrade,attainment_4thgrade,attainment_5thgrade,attainment_6thgrade,attainment_7thgrade,attainment_8thgrade,attainment_9thgrade,attainment_10thgrade,attainment_11thgrade,attainment_12thgradenodiploma,attainment_regularhighschooldiploma,attainment_gedoralternativecredential,attainment_somecollegelessthan1year,attainment_somecollege1ormoreyearsnodegree,attainment_associatesdegree,attainment_bachelorsdegree,attainment_mastersdegree,attainment_professionalschooldegree,attainment_doctoratedegree,classworker_total_series,classworker_privateforprofit,classworker_privateforprofit_employee,classworker_privateforprofit_selfemployedincorporatedbusiness,classworker_privatenotforprofit,classworker_localgovt,classworker_stategovt,classworker_federalgovt,classworker_selfemployednonincorporatedbusiness,classworker_unpaidfamilyworker,lfstatus_total_sexbyagebyemploymentstatus16+_series,lfstatus_mciv_16to19,lfstatus_mciv_16to19_employed,lfstatus_mciv_16to19_unemployed,lfstatus_mciv_20to21,lfstatus_mciv_20to21_employed,lfstatus_mciv_20to21_unemployed,lfstatus_mciv_22to24,lfstatus_mciv_22to24_employed,lfstatus_mciv_22to24_unemployed,lfstatus_mciv_25to29,lfstatus_mciv_25to29_employed,lfstatus_mciv_25to29_unemployed,lfstatus_mciv_30to34,lfstatus_mciv_30to34_employed,lfstatus_mciv_30to34_unemployed,lfstatus_mciv_35to44,lfstatus_mciv_35to44_employed,lfstatus_mciv_35to44_unemployed,lfstatus_mciv_45to54,lfstatus_mciv_45to54_employed,lfstatus_mciv_45to54_unemployed,lfstatus_mciv_55to59,lfstatus_mciv_55to59_employed,lfstatus_mciv_55to59_unemployed,lfstatus_mciv_60to61,lfstatus_mciv_60to61_employed,lfstatus_mciv_60to61_unemployed,lfstatus_mciv_62to64,lfstatus_mciv_62to64_employed,lfstatus_mciv_62to64_unemployed,lfstatus_mciv_65to69,lfstatus_mciv_65to69_employed,lfstatus_mciv_65to69_unemployed,lfstatus_mciv_70to74,lfstatus_mciv_70to74_employed,lfstatus_mciv_70to74_unemployed,lfstatus_mciv_75+,lfstatus_mciv_75+_employed,lfstatus_mciv_75+_unemployed,lfstatus_fciv_16to19,lfstatus_fciv_16to19_employed,lfstatus_fciv_16to19_unemployed,lfstatus_fciv_20to21,lfstatus_fciv_20to21_employed,lfstatus_fciv_20to21_unemployed,lfstatus_fciv_22to24,lfstatus_fciv_22to24_employed,lfstatus_fciv_22to24_unemployed,lfstatus_fciv_25to29,lfstatus_fciv_25to29_employed,lfstatus_fciv_25to29_unemployed,lfstatus_fciv_30to34,lfstatus_fciv_30to34_employed,lfstatus_fciv_30to34_unemployed,lfstatus_fciv_35to44,lfstatus_fciv_35to44_employed,lfstatus_fciv_35to44_unemployed,lfstatus_fciv_45to54,lfstatus_fciv_45to54_employed,lfstatus_fciv_45to54_unemployed,lfstatus_fciv_55to59,lfstatus_fciv_55to59_employed,lfstatus_fciv_55to59_unemployed,lfstatus_fciv_60to61,lfstatus_fciv_60to61_employed,lfstatus_fciv_60to61_unemployed,lfstatus_fciv_62to64,lfstatus_fciv_62to64_employed,lfstatus_fciv_62to64_unemployed,lfstatus_fciv_65to69,lfstatus_fciv_65to69_employed,lfstatus_fciv_65to69_unemployed,lfstatus_fciv_70to74,lfstatus_fciv_70to74_employed,lfstatus_fciv_70to74_unemployed,lfstatus_fciv_75+,lfstatus_fciv_75+_employed,lfstatus_fciv_75+_unemployed,percapita_income,geo_total_series,geo_1to4_total,geo_5to17_total,geo_18to19_total,geo_20to24_total,geo_25to29_total,geo_30to34_total,geo_35to39_total,geo_40to44_total,geo_45to49_total,geo_50to54_total,geo_55to59_total,geo_60to64_total,geo_65to69_total,geo_70to74_total,geo_75+_total,geo_samehouse_total,geo_55to59_samehouse,geo_60to64_samehouse,geo_65to69_samehouse,geo_70to74_samehouse,geo_75+_samehouse,geo_movedsamecounty_total,geo_55to59_movedsamecounty,geo_60to64_movedsamecounty,geo_65to69_movedsamecounty,geo_70to74_movedsamecounty,geo_75+_movedsamecounty,geo_moveddifferentcountysamestate_total,geo_55to59_moveddifferentcountysamestate,geo_60to64_moveddifferentcountysamestate,geo_65to69_moveddifferentcountysamestate,geo_70to74_moveddifferentcountysamestate,geo_75+_moveddifferentcountysamestate,geo_moveddifferentstate_total,geo_55to59_moveddifferentstate,geo_60to64_moveddifferentstate,geo_65to69_moveddifferentstate,geo_70to74_moveddifferentstate,geo_75+_moveddifferentstate,geo_movedabroad_total,geo_55to59_movedabroad,geo_60to64_movedabroad,geo_65to69_movedabroad,geo_70to74_movedabroad,geo_75+_movedabroad,vehicles_tenurebyvehicles_total_series,vehicles_ownerocc_total,vehicles_ownerocc_novehicle,vehicles_ownerocc_1vehicle,vehicles_ownerocc_2vehicles,vehicles_ownerocc_3vehicles,vehicles_ownerocc_4vehicles,vehicles_ownerocc_5+vehicles,vehicles_renterocc_total,vehicles_renterocc_novehicle,vehicles_renterocc_1vehicle,vehicles_renterocc_2vehicles,vehicles_renterocc_3vehicles,vehicles_renterocc_4vehicles,vehicles_renterocc_5+vehicles,industry_sexbyindustrycivilianpop_total_series,industry_sexbyindustrycivilianpop_totalmale,industry_m_agriculture_forestry_fishing_hunting_mining,industry_m_agmining_agriculture_forestry_fishing_hunting,industry_m_agmining_mining_quarrying_oilandgas,industry_m_construction,industry_m_manufacturing,industry_m_wholesaletrade,industry_m_retailtrade,industry_m_transportation_warehousing_utilities,industry_m_transut_transportation_warehousing,industry_m_transut_utilities,industry_m_information,industry_m_finance_insurance_realestate_rental,industry_m_finrent_finance_insurance,industry_m_finrent_realestate_rental,industry_m_professional_scientific_managementadmin_waste,industry_m_profwaste_professional_scientific_technicalservices,industry_m_profwaste_managementcompaniesenterprises,industry_m_adminandsupportandwaste,industry_m_educational_healthcare_socialassistance,industry_m_edsocial_educational,industry_m_edsocial_healthcare_socialassistance,industry_m_arts_entertainmentrec_accommodation_food,industry_m_artsaccom_arts_entertainmentrec,industry_m_artsaccom_accommodation_food,industry_m_otherservices_notpublicadmin,industry_m_publicadmin,industry_sexbyindustrycivilianpop_totalfemale,industry_f_agriculture_forestry_fishing_hunting_mining,industry_f_agmining_agriculture_forestry_fishing_hunting,industry_f_agmining_mining_quarrying_oilandgas,industry_f_construction,industry_f_manufacturing,industry_f_wholesaletrade,industry_f_retailtrade,industry_f_transportation_warehousing_utilities,industry_f_transut_transportation_warehousing,industry_f_transut_utilities,industry_f_information,industry_f_finance_insurance_realestate_rental,industry_f_finrent_finance_insurance,industry_f_finrent_realestate_rental,industry_f_professional_scientific_managementadmin_waste,industry_f_profwaste_professional_scientific_technicalservices,industry_f_profwaste_managementcompaniesenterprises,industry_f_adminandsupportandwaste,industry_f_educational_healthcare_socialassistance,industry_f_edsocial_educational,industry_f_edsocial_healthcare_socialassistance,industry_f_arts_entertainmentrec_accommodation_food,industry_f_artsaccom_arts_entertainmentrec,industry_f_artsaccom_accommodation_food,industry_f_otherservices_notpublicadmin,industry_f_publicadmin,occupation_sexbyoccupationcivilianpop_total_series,occupation_sexbyoccupationcivilianpop_totalmale,occupation_m_management,occupation_m_businessandfinancial,occupation_m_computerandmathematical,occupation_m_architectureandengineering,occupation_m_lifephysicalsocialscience,occupation_m_communityandsocialservices,occupation_m_legal,occupation_m_educationtrainingandlibrary,occupation_m_artsdesignentertainmentsportsandmedia,occupation_m_healthcarepractitionersandtechnical,occupation_m_healthcaresupport,occupation_m_protectiveservice,occupation_m_foodprepandserving,occupation_m_buildingandgroundscleaningandmaintenance,occupation_m_personalcareandservice,occupation_m_salesandrelated,occupation_m_officeandadmin,occupation_m_farmingfishingandforestry,occupation_m_constructionandextraction,occupation_m_installationmaintenanceandrepair,occupation_m_production,occupation_m_transportation,occupation_m_materialmoving,occupation_sexbyoccupationcivilianpop_totalfemale,occupation_f_management,occupation_f_businessandfinancial,occupation_f_computerandmathematical,occupation_f_architectureandengineering,occupation_f_lifephysicalsocialscience,occupation_f_communityandsocialservices,occupation_f_legal,occupation_f_educatio

In [137]:
ok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Columns: 1219 entries, NAME to GeoFIPS
dtypes: float64(1218), object(1)
memory usage: 514.4+ KB

In [138]:
ok.to_csv('../data/ACS20205YR.csv', index = False)